const chronicles = {
  'crónica1': {
    text: `PLAZOLETA DE SAN JUAN DE DIOS. Fue construída en 1732 en Maracaibo. En un tiempo fue llamada Plaza de la Libertad, hoy conocida como plazoleta de la Basílica. Desde su construcción hace varios siglos, allí se han efectuado grandes concentraciones tales como las fiestas patronales de Nuestra Señora de Chiquinquirá aún vigentes, los carnavales, y a principios de 1900 hubo cine mudo gratis y al aire libre.`,
    words: [
      'PLAZOLETA', 'DE', 'SAN', 'JUAN', 'DE', 'DIOS', 'Fue', 'construída', 'en', '1732', 'en', 'Maracaibo', 'En', 'un', 'tiempo', 'fue', 'llamada', 'Plaza', 'de', 'la', 'Libertad', 'hoy', 'conocida', 'como', 'plazoleta', 'de', 'la', 'Basílica', 'Desde', 'su', 'construcción', 'hace', 'varios', 'siglos', 'allí', 'se', 'han', 'efectuado', 'grandes', 'concentraciones', 'tales', 'como', 'las', 'fiestas', 'patronales', 'de', 'Nuestra', 'Señora', 'de', 'Chiquinquirá', 'aún', 'vigentes', 'los', 'carnavales', 'y', 'a', 'principios', 'de', '1900', 'hubo', 'cine', 'mudo', 'gratis', 'y', 'al', 'aire', 'libre'
    ],
    wordCount: 67 // Actualizado con el total de palabras
  },
  'crónica2': {
    text: `ERMITA DE SAN JUAN DE DIOS. Lugar de oración y recogimiento que le permite al fraile o ermitaño poder cultivar en paz su propia vocación de fe. En 1668, el capitán Don Juan de las Nieves de Andrade construyó y financió en un lugar despoblado, una pequeña ermita para exaltar el culto a San Juan de Dios. Era una capilla rústica con paredes de barro, techo de eneas y palma. Con el poder de Dios y el fervor de un pueblo, a partir del milagro de la aparición de la Virgen en la tablita, esa pequeña ermita de San Juan de Dios se transformaría con el paso del tiempo en la actual Basílica de Nuestra Señora de Chiquinquirá y San Juan de Dios.`,
    words: [
      'ERMITA', 'DE', 'SAN', 'JUAN', 'DE', 'DIOS', 'Lugar', 'de', 'oración', 'y', 'recogimiento', 'que', 'le', 'permite', 'al', 'fraile', 'o', 'ermitaño', 'poder', 'cultivar', 'en', 'paz', 'su', 'propia', 'vocación', 'de', 'fe', 'En', '1668', 'el', 'capitán', 'Don', 'Juan', 'de', 'las', 'Nieves', 'de', 'Andrade', 'construyó', 'y', 'financió', 'en', 'un', 'lugar', 'despoblado', 'una', 'pequeña', 'ermita', 'para', 'exaltar', 'el', 'culto', 'a', 'San', 'Juan', 'de', 'Dios', 'Era', 'una', 'capilla', 'rústica', 'con', 'paredes', 'de', 'barro', 'techo', 'de', 'eneas', 'y', 'palma', 'Con', 'el', 'poder', 'de', 'Dios', 'y', 'el', 'fervor', 'de', 'un', 'pueblo', 'a', 'partir', 'del', 'milagro', 'de', 'la', 'aparición', 'de', 'la', 'Virgen', 'en', 'la', 'tablita', 'esa', 'pequeña', 'ermita', 'de', 'San', 'Juan', 'de', 'Dios', 'se', 'transformaría', 'con', 'el', 'paso', 'del', 'tiempo', 'en', 'la', 'actual', 'Basílica', 'de', 'Nuestra', 'Señora', 'de', 'Chiquinquirá', 'y', 'San', 'Juan', 'de', 'Dios'
    ],
    wordCount: 108 // Actualizado con el total de palabras, excluyendo signos de puntuación
  },
  'crónica3': {
    text: `EL MILAGRO DE LA TABLITA. En 1709, ocurrió en Maracaibo el milagro de la tablita. Una señora encuentra la tablita a orillas del Lago de Maracaibo y la coloca como tapa de un tinajero. Días más tarde escuchó un golpeteo y unas luces que provenían de su casa, al entrar, encontró en la tablita la imagen resplandeciente de la Virgen y el Niño junto a San Antonio y San Andrés. La imagen en la tablita se convirtió en objeto de peregrinación para los devotos. La tablita fue trasladada a la ermita de San Juan de Dios, reposando desde entonces en el mismo lugar, hoy transformado en nuestra amada Basílica. Cuentan que su aposento actual lo seleccionó nuestra mismísima Señora de Chiquinquirá al negarse a ser trasladada a la Catedral. Se dice que la tablita se puso tan pesada, que fue sólo entonces cuando se decidió devolverla a la iglesia San Juan de Dios, cerca de donde apareció por primera vez cuando recuperó su peso original y pudo ser trasladada.`,
    words: [
      'EL', 'MILAGRO', 'DE', 'LA', 'TABLITA', 'En', '1709', 'ocurrió', 'en', 'Maracaibo', 'el', 'milagro', 'de', 'la', 'tablita', 'Una', 'señora', 'encuentra', 'la', 'tablita', 'a', 'orillas', 'del', 'Lago', 'de', 'Maracaibo', 'y', 'la', 'coloca', 'como', 'tapa', 'de', 'un', 'tinajero', 'Días', 'más', 'tarde', 'escuchó', 'un', 'golpeteo', 'y', 'unas', 'luces', 'que', 'provenían', 'de', 'su', 'casa', 'al', 'entrar', 'encontró', 'en', 'la', 'tablita', 'la', 'imagen', 'resplandeciente', 'de', 'la', 'Virgen', 'y', 'el', 'Niño', 'junto', 'a', 'San', 'Antonio', 'y', 'San', 'Andrés', 'La', 'imagen', 'en', 'la', 'tablita', 'se', 'convirtió', 'en', 'objeto', 'de', 'peregrinación', 'para', 'los', 'devotos', 'La', 'tablita', 'fue', 'trasladada', 'a', 'la', 'ermita', 'de', 'San', 'Juan', 'de', 'Dios', 'reposando', 'desde', 'entonces', 'en', 'el', 'mismo', 'lugar', 'hoy', 'transformado', 'en', 'nuestra', 'amada', 'Basílica', 'Cuentan', 'que', 'su', 'aposento', 'actual', 'lo', 'seleccionó', 'nuestra', 'mismísima', 'Señora', 'de', 'Chiquinquirá', 'al', 'negarse', 'a', 'ser', 'trasladada', 'a', 'la', 'Catedral', 'Se', 'dice', 'que', 'la', 'tablita', 'se', 'puso', 'tan', 'pesada', 'que', 'fue', 'sólo', 'entonces', 'cuando', 'se', 'decidió', 'devolverla', 'a', 'la', 'iglesia', 'San', 'Juan', 'de', 'Dios', 'cerca', 'de', 'donde', 'apareció', 'por', 'primera', 'vez', 'cuando', 'recuperó', 'su', 'peso', 'original', 'y', 'pudo', 'ser', 'trasladada'
      // Nota: Aquí se incluyen todas las palabras en el orden en que aparecen, sin los índices de posición explícitos para simplificar
    ],
    wordCount: 169 // Total de palabras contadas
  },
  'crónica4': {
    text: `PLAZA URDANETA. Mediante decreto fechado el 10 de julio de 1888, el gobernador del Zulia, doctor Alejandro Andrade, ordena la construcción de una plaza dedicada al general en jefe Rafael Urdaneta y el 3 de agosto del mismo año, el Gobierno nacional decreta la erección de una estatua de nuestro máximo héroe regional, como parte de los actos del centenario de su natalicio, el 24 de octubre de 1888. Esta plaza estará ubicada en el sitio denominado El Circo, adquiriendo un viejo caserón que existía, para completar el cuadrilátero que tenía de 100 metros por lado. La inauguración tuvo que postergarse por no haber llegado el pedestal y fue celebrada en diciembre del mismo año. La Junta, como homenaje a Urdaneta, promueve un certamen poético que ganó el zuliano Udón Pérez con el soneto Ofrenda, el cual fue grabado en losa de mármol y colocado en el pedestal de la estatua pedestre de Rafael Urdaneta.`,
    words: [
      'PLAZA', 'URDANETA', 'Mediante', 'decreto', 'fechado', 'el', '10', 'de', 'julio', 'de', '1888', 'el', 'gobernador', 'del', 'Zulia', 'doctor', 'Alejandro', 'Andrade', 'ordena', 'la', 'construcción', 'de', 'una', 'plaza', 'dedicada', 'al', 'general', 'en', 'jefe', 'Rafael', 'Urdaneta', 'y', 'el', '3', 'de', 'agosto', 'del', 'mismo', 'año', 'el', 'Gobierno', 'nacional', 'decreta', 'la', 'erección', 'de', 'una', 'estatua', 'de', 'nuestro', 'máximo', 'héroe', 'regional', 'como', 'parte', 'de', 'los', 'actos', 'del', 'centenario', 'de', 'su', 'natalicio', 'el', '24', 'de', 'octubre', 'de', '1888', 'Esta', 'plaza', 'estará', 'ubicada', 'en', 'el', 'sitio', 'denominado', 'El', 'Circo', 'adquiriendo', 'un', 'viejo', 'caserón', 'que', 'existía', 'para', 'completar', 'el', 'cuadrilátero', 'que', 'tenía', 'de', '100', 'metros', 'por', 'lado', 'La', 'inauguración', 'tuvo', 'que', 'postergarse', 'por', 'no', 'haber', 'llegado', 'el', 'pedestal', 'y', 'fue', 'celebrada', 'en', 'diciembre', 'del', 'mismo', 'año', 'La', 'Junta', 'como', 'homenaje', 'a', 'Urdaneta', 'promueve', 'un', 'certamen', 'poético', 'que', 'ganó', 'el', 'zuliano', 'Udón', 'Pérez', 'con', 'el', 'soneto', 'Ofrenda', 'el', 'cual', 'fue', 'grabado', 'en', 'losa', 'de', 'mármol', 'y', 'colocado', 'en', 'el', 'pedestal', 'de', 'la', 'estatua', 'pedestre', 'de', 'Rafael', 'Urdaneta'
      // Nota: Aquí se incluyen todas las palabras en el orden en que aparecen, sin los índices de posición explícitos para simplificar
    ],
    wordCount: 156 // Total de palabras contadas
  },
  'crónica5': {
    text: `FAMOSOS CEPILLADEROS DE MARACAIBO. Hermes Cerrudo fue uno de los más famosos cepilladeros de Maracaibo, un personaje querido por niños y adultos de los años 30 y 40. Su pequeño negocio de cepillados y frutas era el sitio obligado para calmar la sed de los escolares de la época con variados sabores: frambuesa, limón, tamarindo, menta, guayaba, níspero, piña, coco, chirimoya y guanábana. Caracterizados con la modalidad, adoptada por Cerrudo, de agregar leche condensada. Su negocio se convirtió en punto de referencia en la ciudad como La Cuadra de Cerrudo.`,
    words: [
'FAMOSOS', 'CEPILLADEROS', 'DE', 'MARACAIBO', 'Hermes', 'Cerrudo', 'fue', 'uno', 'de', 'los', 'más', 'famosos', 'cepilladeros', 'de', 'Maracaibo', 'un', 'personaje', 'querido', 'por', 'niños', 'y', 'adultos', 'de', 'los', 'años', '30', 'y', '40', 'Su', 'pequeño', 'negocio', 'de', 'cepillados', 'y', 'frutas', 'era', 'el', 'sitio', 'obligado', 'para', 'calmar', 'la', 'sed', 'de', 'los', 'escolares', 'de', 'la', 'época', 'con', 'variados', 'sabores', 'frambuesa', 'limón', 'tamarindo', 'menta', 'guayaba', 'níspero', 'piña', 'coco', 'chirimoya', 'y', 'guanábana', 'Caracterizados', 'con', 'la', 'modalidad', 'adoptada', 'por', 'Cerrudo', 'de', 'agregar', 'leche', 'condensada', 'Su', 'negocio', 'se', 'convirtió', 'en', 'punto', 'de', 'referencia', 'en', 'la', 'ciudad', 'como', 'La', 'Cuadra', 'de', 'Cerrudo'
      // Nota: Aquí se incluyen todas las palabras en el orden en que aparecen, sin los índices de posición explícitos para simplificar
    ],
    wordCount: 91 // Total de palabras contadas
  },
  'crónica6': {
    text: ` EL CÍRCULO ARTÍSTICO DEL ZULIA. Asociación de artistas sin fines de lucro. El Círculo Artístico del Zulia fue una escuela de pintura y escultura totalmente gratuita para niños y jóvenes, fundada en 1916 por Don Julio Árraga, quien fue su primer director y otros ilustres personajes como don Manuel Puchi Fonseca y don Neptali Rincon. Por muchos años el Círculo funcionó en la Calle Ciencias o Calle Derecha, como se le conocía en ese entonces.`,
    words: [
'EL', 'CÍRCULO', 'ARTÍSTICO', 'DEL', 'ZULIA', 'Asociación', 'de', 'artistas', 'sin', 'fines', 'de', 'lucro', 'El', 'Círculo', 'Artístico', 'del', 'Zulia', 'fue', 'una', 'escuela', 'de', 'pintura', 'y', 'escultura', 'totalmente', 'gratuita', 'para', 'niños', 'y', 'jóvenes', 'fundada', 'en', '1916', 'por', 'Don', 'Julio', 'Árraga', 'quien', 'fue', 'su', 'primer', 'director', 'y', 'otros', 'ilustres', 'personajes', 'como', 'don', 'Manuel', 'Puchi', 'Fonseca', 'y', 'don', 'Neptali', 'Rincon', 'Por', 'muchos', 'años', 'el', 'Círculo', 'funcionó', 'en', 'la', 'Calle', 'Ciencias', 'o', 'Calle', 'Derecha', 'como', 'se', 'le', 'conocía', 'en', 'ese', 'entonces'
      // Nota: Aquí se incluyen todas las palabras en el orden en que aparecen, sin los índices de posición explícitos para simplificar
    ],
    wordCount: 156 // Total de palabras contadas
  },
  'crónica7': {
    text: ` MARACAIBO, LA PRIMERA CIUDAD DE VENEZUELA EN PROYECTAR PELÍCULAS. El vitascopio fue un proyector de cine inventado por Thomas Alva Edison en 1895, exhibido el 28 de enero de 1897 por primera vez en la ciudad de Maracaibo, en Venezuela y probablemente en Latinoamérica; por los hermanos Manuel y Guillermo Trujillo Durán, exitosos empresarios, quienes proyectaron en el Teatro Baralt dos películas filmadas por Manuel; Muchachas bañándose en el Lago y Un gran especialista sacando muelas en el Hotel Europa.`,
    words: [
' MARACAIBO', ' LA', ' PRIMERA', ' CIUDAD', ' DE', ' VENEZUELA', ' EN', ' PROYECTAR', ' PELÍCULAS', ' El', ' vitascopio', ' fue', ' un', ' proyector', ' de', ' cine', ' inventado', ' por', ' Thomas', ' Alva', ' Edison', ' en', ' 1895', ' exhibido', ' el', ' 28', ' de', ' enero', ' de', ' 1897', ' por', ' primera', ' vez', ' en', ' la', ' ciudad', ' de', ' Maracaibo', ' en', ' Venezuela', ' y', ' probablemente', ' en', ' Latinoamérica', ' por', ' los', ' hermanos', ' Manuel', ' y', ' Guillermo', ' Trujillo', ' Durán', ' exitosos', ' empresarios', ' quienes', ' proyectaron', ' en', ' el', ' Teatro', ' Baralt', ' dos', ' películas', ' filmadas', ' por', ' Manuel', ' Muchachas', ' bañándose', ' en', ' el', ' Lago', ' y', ' Un', ' gran', ' especialista', ' sacando', ' muelas', ' en', ' el', ' Hotel', ' Europa'
      // Nota: Aquí se incluyen todas las palabras en el orden en que aparecen, sin los índices de posición explícitos para simplificar
    ],
    wordCount: 156 // Total de palabras contadas
  },
'crónica8': {
    text: ` EL CINE ALCÁZAR. El cine Alcázar funcionó en la ciudad de Maracaibo, en la esquina de las calles Ciencias con Obispo Lazo frente al lado sur de la Plaza Bolívar, a finales de la década de 1920 hasta principios de la de 1930, época dorada del cine mudo.`,
    words: [
'EL', 'CINE', 'ALCÁZAR', 'El', 'cine', 'Alcázar', 'funcionó', 'en', 'la', 'ciudad', 'de', 'Maracaibo', 'en', 'la', 'esquina', 'de', 'las', 'calles', 'Ciencias', 'con', 'Obispo', 'Lazo', 'frente', 'al', 'lado', 'sur', 'de', 'la', 'Plaza', 'Bolívar', 'a', 'finales', 'de', 'la', 'década', 'de', '1920', 'hasta', 'principios', 'de', 'la', 'de', '1930', 'época', 'dorada', 'del', 'cine', 'mudo'
      // Nota: Aquí se incluyen todas las palabras en el orden en que aparecen, sin los índices de posición explícitos para simplificar
    ],
    wordCount: 156 // Total de palabras contadas
  },
'crónica9': {
    text: ` LA CALLE DEL MILAGRO. En la Maracaibo de 1700, la calle del Milagro, era una callecita angosta de unas 10 cuadras de largo que en su extremo norte salía desde el sector llamado El Mosquito y llegaba a la parte posterior del Mercado del Lago, mejor conocido como el Mercado de los Buchones, por la cantidad de buchones que descansaban en su techo. La calle adquirió ese nombre debido a la aparición de la tablita con la imagen de la Virgen Nuestra Señora de Chiquinquirá, hecho considerado un milagro al correr del siglo XVIII hasta nuestros días.`,
    words: [
'LA', 'CALLE', 'DEL', 'MILAGRO', 'En', 'la', 'Maracaibo', 'de', '1700', 'la', 'calle', 'del', 'Milagro', 'era', 'una', 'callecita', 'angosta', 'de', 'unas', '10', 'cuadras', 'de', 'largo', 'que', 'en', 'su', 'extremo', 'norte', 'salía', 'desde', 'el', 'sector', 'llamado', 'El', 'Mosquito', 'y', 'llegaba', 'a', 'la', 'parte', 'posterior', 'del', 'Mercado', 'del', 'Lago', 'mejor', 'conocido', 'como', 'el', 'Mercado', 'de', 'los', 'Buchones', 'por', 'la', 'cantidad', 'de', 'buchones', 'que', 'descansaban', 'en', 'su', 'techo', 'La', 'calle', 'adquirió', 'ese', 'nombre', 'debido', 'a', 'la', 'aparición', 'de', 'la', 'tablita', 'con', 'la', 'imagen', 'de', 'la', 'Virgen', 'Nuestra', 'Señora', 'de', 'Chiquinquirá', 'hecho', 'considerado', 'un', 'milagro', 'al', 'correr', 'del', 'siglo', 'XVIII', 'hasta', 'nuestros', 'días'
      // Nota: Aquí se incluyen todas las palabras en el orden en que aparecen, sin los índices de posición explícitos para simplificar
    ],
    wordCount: 156 // Total de palabras contadas
  },
'crónica10': {
    text: `LA CALLE CIENCIAS O CALLE DERECHA. En la Maracaibo de las primeras décadas de 1900, la calle Ciencias o calle Derecha, era la calle de las escuelas y colegios de Maracaibo. El Sr. Gabriel Franchi Molina en su libro Maracaibo antes de hoy, dice: “Los maracaiberos de esos tiempos solíamos decir, que cuando los muchachos salían de los colegios, llenaban la calle Ciencias como las taritas llenaban la ciudad en un día de San Juan”. Igualmente vivían en ella muchas familias distinguidas de nuestra ciudad.`,
    words: [
        'LA', 'CALLE', 'CIENCIAS', 'O', 'CALLE', 'DERECHA', 'En', 'la', 'Maracaibo', 'de', 'las', 'primeras', 'décadas', 'de', '1900', 'la', 'calle', 'Ciencias', 'o', 'calle', 'Derecha', 'era', 'la', 'calle', 'de', 'las', 'escuelas', 'y', 'colegios', 'de', 'Maracaibo', 'El', 'Sr', 'Gabriel', 'Franchi', 'Molina', 'en', 'su', 'libro', 'Maracaibo', 'antes', 'de', 'hoy', 'dice', 'Los', 'maracaiberos', 'de', 'esos', 'tiempos', 'solíamos', 'decir', 'que', 'cuando', 'los', 'muchachos', 'salían', 'de', 'los', 'colegios', 'llenaban', 'la', 'calle', 'Ciencias', 'como', 'las', 'taritas', 'llenaban', 'la', 'ciudad', 'en', 'un', 'día', 'de', 'San', 'Juan', 'Igualmente', 'vivían', 'en', 'ella', 'muchas', 'familias', 'distinguidas', 'de', 'nuestra', 'ciudad'
    ],
    wordCount: 125
  },
  'crónica11': {
    text: `EL CRISTO NEGRO DE GIBRALTAR. Gibraltar es el nombre de la población situada al sur del Lago de Maracaibo, fundada 1591 por el capitán Gonzalo de Piña Lidueña. Lugar de origen de El Cristo Negro de Gibraltar que en 1660 fue rescatado y traído a Maracaibo luego del incendio provocado por los indios quiriquires que destruyó la población, cuyas casas tenían techos de paja, igual que la iglesia. En 1620, los gibraltareños solicitaron su devolución a las autoridades de la época, situación no permitida por los fieles marabinos. El conflicto se resolvió al colocar al Cristo en el Lago de Maracaibo, sobre una canoa para que sus olas lo trasladaran donde él quisiera quedarse. Después de tres intentos, las tres veces arribó a las costas del Lago de Maracaibo, lo que sería considerado por la población un milagro del Cristo Negro por eso al sector se le dio el nombre de El Milagro. Al pasar el tiempo y construirse la carretera, pasó a denominarse avenida El Milagro. Desde entonces El Cristo Negro es venerado en la Catedral de Maracaibo.`,
    words: [
        'EL', 'CRISTO', 'NEGRO', 'DE', 'GIBRALTAR', 'Gibraltar', 'es', 'el', 'nombre', 'de', 'la', 'población', 'situada', 'al', 'sur', 'del', 'Lago', 'de', 'Maracaibo', 'fundada', '1591', 'por', 'el', 'capitán', 'Gonzalo', 'de', 'Piña', 'Lidueña', 'Lugar', 'de', 'origen', 'de', 'El', 'Cristo', 'Negro', 'de', 'Gibraltar', 'que', 'en', '1660', 'fue', 'rescatado', 'y', 'traído', 'a', 'Maracaibo', 'luego', 'del', 'incendio', 'provocado', 'por', 'los', 'indios', 'quiriquires', 'que', 'destruyó', 'la', 'población', 'cuyas', 'casas', 'tenían', 'techos', 'de', 'paja', 'igual', 'que', 'la', 'iglesia', 'En', '1620', 'los', 'gibraltareños', 'solicitaron', 'su', 'devolución', 'a', 'las', 'autoridades', 'de', 'la', 'época', 'situación', 'no', 'permitida', 'por', 'los', 'fieles', 'marabinos', 'El', 'conflicto', 'se', 'resolvió', 'al', 'colocar', 'al', 'Cristo', 'en', 'el', 'Lago', 'de', 'Maracaibo', 'sobre', 'una', 'canoa', 'para', 'que', 'sus', 'olas', 'lo', 'trasladaran', 'donde', 'él', 'quisiera', 'quedarse', 'Después', 'de', 'tres', 'intentos', 'las', 'tres', 'veces', 'arribó', 'a', 'las', 'costas', 'del', 'Lago', 'de', 'Maracaibo', 'lo', 'que', 'sería', 'considerado', 'por', 'la', 'población', 'un', 'milagro', 'del', 'Cristo', 'Negro', 'por', 'eso', 'al', 'sector', 'se', 'le', 'dio', 'el', 'nombre', 'de', 'El', 'Milagro', 'Al', 'pasar', 'el', 'tiempo', 'y', 'construirse', 'la', 'carretera', 'pasó', 'a', 'denominarse', 'avenida', 'El', 'Milagro', 'Desde', 'entonces', 'El', 'Cristo', 'Negro', 'es', 'venerado', 'en', 'la', 'Catedral', 'de', 'Maracaibo'
    ],
    wordCount: 250
  },
  'crónica12': {
    text: `MARACAIBO, LA PRIMERA CIUDAD DE VENEZUELA EN CONTAR CON ALUMBRADO PÚBLICO. En la Maracaibo de 1848 aún no existía el servicio de alumbrado público. La gente tenía la obligación de colocar faroles en las puertas o ventanas entre las 6 de la tarde y las 10 de la noche. Antes de existir el servicio eléctrico, la población maracaibera se alumbraba con estacas o teas impregnadas de grasa animal, candiles de barro, aceite de coco, hasta que llegaron las lámparas de querosén. El 24 de octubre de 1888, en el centenario del Natalicio del General Rafael Urdaneta, se inauguró en Maracaibo el alumbrado eléctrico, primero de su clase en Venezuela. La primera compañía en administrar este servicio público se llamó The Maracaibo Electric Light Company. El servicio doméstico constaba de 3200 lámparas incandescentes. Ese 24 de octubre de 1888, entró en servicio la energía eléctrica con el alumbrado público de la ciudad. - Un año después se extendió al servicio doméstico. Fuimos la primera ciudad de Venezuela que tuvo alumbrado público.`,
    words: [
        'MARACAIBO', 'LA', 'PRIMERA', 'CIUDAD', 'DE', 'VENEZUELA', 'EN', 'CONTAR', 'CON', 'ALUMBRADO', 'PÚBLICO', 'En', 'la', 'Maracaibo', 'de', '1848', 'aún', 'no', 'existía', 'el', 'servicio', 'de', 'alumbrado', 'público', 'La', 'gente', 'tenía', 'la', 'obligación', 'de', 'colocar', 'faroles', 'en', 'las', 'puertas', 'o', 'ventanas', 'entre', 'las', '6', 'de', 'la', 'tarde', 'y', 'las', '10', 'de', 'la', 'noche', 'Antes', 'de', 'existir', 'el', 'servicio', 'eléctrico', 'la', 'población', 'maracaibera', 'se', 'alumbraba', 'con', 'estacas', 'o', 'teas', 'impregnadas', 'de', 'grasa', 'animal', 'candiles', 'de', 'barro', 'aceite', 'de', 'coco', 'hasta', 'que', 'llegaron', 'las', 'lámparas', 'de', 'querosén', 'El', '24', 'de', 'octubre', 'de', '1888', 'en', 'el', 'centenario', 'del', 'Natalicio', 'del', 'General', 'Rafael', 'Urdaneta', 'se', 'inauguró', 'en', 'Maracaibo', 'el', 'alumbrado', 'eléctrico', 'primero', 'de', 'su', 'clase', 'en', 'Venezuela', 'La', 'primera', 'compañía', 'en', 'administrar', 'este', 'servicio', 'público', 'se', 'llamó', 'The', 'Maracaibo', 'Electric', 'Light', 'Company', 'El', 'servicio', 'doméstico', 'constaba', 'de', '3200', 'lámparas', 'incandescentes', 'Ese', '24', 'de', 'octubre', 'de', '1888', 'entró', 'en', 'servicio', 'la', 'energía', 'eléctrica', 'con', 'el', 'alumbrado', 'público', 'de', 'la', 'ciudad', 'Un', 'año', 'después', 'se', 'extendió', 'al', 'servicio', 'doméstico', 'Fuimos', 'la', 'primera', 'ciudad', 'de', 'Venezuela', 'que', 'tuvo', 'alumbrado', 'público'
    ],
    wordCount: 207
  },
  'crónica13': {
    text: `MARACAIBERO, MARABINO O MARACUCHO. A los oriundos o nacidos en la Ciudad del Sol Amada se les llama maracaiberos, marabinos o maracuchos. El término maracucho fue usado por mucho tiempo de forma despectiva por su terminación ucho pero ha sido aceptado por la Real Academia de la Lengua Española y por supuesto, por los nacidos en la capital zuliana. Según el diccionario general del Zulia (Hernández y Parra, 1999) el término maracucho-a entró al léxico en 1912. La fuerza vocal de esta palabra hizo que fuese asimilada y aceptada por el pueblo. Maracucho es una expresión popular y coloquial que refleja la idiosincrasia de la ciudad y que honra a sus habitantes. Por mucho tiempo se consideró, incluso todavía algunos piensan que la forma correcta de llamar a los nacidos en Maracaibo es maracaibero-a , porque es un término más elegante, respetuoso y es la palabra que debe usarse para plasmarla en escritos, narraciones formales y discursos. El término marabino es rebuscado, sofisticado, afectado, refistolero y sifrino, cosa que no cabe dentro de la manera de ser sencilla de nuestro pueblo, por lo cual debe ser rechazado. En conclusión, -maracucho y maracaibero- significan lo mismo, pero se utilizan en situaciones diferentes.`,
    words: [
        'MARACAIBERO', 'MARABINO', 'O', 'MARACUCHO', 'A', 'los', 'oriundos', 'o', 'nacidos', 'en', 'la', 'Ciudad', 'del', 'Sol', 'Amada', 'se', 'les', 'llama', 'maracaiberos', 'marabinos', 'o', 'maracuchos', 'El', 'término', 'maracucho', 'fue', 'usado', 'por', 'mucho', 'tiempo', 'de', 'forma', 'despectiva', 'por', 'su', 'terminación', 'ucho', 'pero', 'ha', 'sido', 'aceptado', 'por', 'la', 'Real', 'Academia', 'de', 'la', 'Lengua', 'Española', 'y', 'por', 'supuesto', 'por', 'los', 'nacidos', 'en', 'la', 'capital', 'zuliana', 'Según', 'el', 'diccionario', 'general', 'del', 'Zulia', 'Hernández', 'y', 'Parra', '1999', 'el', 'término', 'maracucho', 'a', 'entró', 'al', 'léxico', 'en', '1912', 'La', 'fuerza', 'vocal', 'de', 'esta', 'palabra', 'hizo', 'que', 'fuese', 'asimilada', 'y', 'aceptada', 'por', 'el', 'pueblo', 'Maracucho', 'es', 'una', 'expresión', 'popular', 'y', 'coloquial', 'que', 'refleja', 'la', 'idiosincrasia', 'de', 'la', 'ciudad', 'y', 'que', 'honra', 'a', 'sus', 'habitantes', 'Por', 'mucho', 'tiempo', 'se', 'consideró', 'incluso', 'todavía', 'algunos', 'piensan', 'que', 'la', 'forma', 'correcta', 'de', 'llamar', 'a', 'los', 'nacidos', 'en', 'Maracaibo', 'es', 'maracaibero', 'a', 'porque', 'es', 'un', 'término', 'más', 'elegante', 'respetuoso', 'y', 'es', 'la', 'palabra', 'que', 'debe', 'usarse', 'para', 'plasmarla', 'en', 'escritos', 'narraciones', 'formales', 'y', 'discursos', 'El', 'término', 'marabino', 'es', 'rebuscado', 'sofisticado', 'afectado', 'refistolero', 'y', 'sifrino', 'cosa', 'que', 'no', 'cabe', 'dentro', 'de', 'la', 'manera', 'de', 'ser', 'sencilla', 'de', 'nuestro', 'pueblo', 'por', 'lo', 'cual', 'debe', 'ser', 'rechazado', 'En', 'conclusión', 'maracucho', 'y', 'maracaibero', 'significan', 'lo', 'mismo', 'pero', 'se', 'utilizan', 'en', 'situaciones', 'diferentes'
    ],
    wordCount: 323
  },
  'crónica14': {
    text: `LA CATEDRAL DE MARACAIBO. El título de matriz, según la costumbre más antigua, es lo que distingue a una iglesia como la primera construida en una ciudad. Nuestra pequeña iglesia matriz fue construida con techos de enea en medio de dos cementerios. Nuestra Santa iglesia Catedral fue llamada inicialmente como la iglesia de San Pedro y San Pablo. El libro más antiguo encontrado en nuestra iglesia matriz, fue el libro parroquial de matrimonios, abierto el 4 de julio de 1610. Fue la primera iglesia construida en Maracaibo, aun cuando su estructura original ya no existe.`,
    words: [
        'LA', 'CATEDRAL', 'DE', 'MARACAIBO', 'El', 'título', 'de', 'matriz', 'según', 'la', 'costumbre', 'más', 'antigua', 'es', 'lo', 'que', 'distingue', 'a', 'una', 'iglesia', 'como', 'la', 'primera', 'construida', 'en', 'una', 'ciudad', 'Nuestra', 'pequeña', 'iglesia', 'matriz', 'fue', 'construida', 'con', 'techos', 'de', 'enea', 'en', 'medio', 'de', 'dos', 'cementerios', 'Nuestra', 'Santa', 'iglesia', 'Catedral', 'fue', 'llamada', 'inicialmente', 'como', 'la', 'iglesia', 'de', 'San', 'Pedro', 'y', 'San', 'Pablo', 'El', 'libro', 'más', 'antiguo', 'encontrado', 'en', 'nuestra', 'iglesia', 'matriz', 'fue', 'el', 'libro', 'parroquial', 'de', 'matrimonios', 'abierto', 'el', '4', 'de', 'julio', 'de', '1610', 'Fue', 'la', 'primera', 'iglesia', 'construida', 'en', 'Maracaibo', 'aun', 'cuando', 'su', 'estructura', 'original', 'ya', 'no', 'existe'
    ],
    wordCount: 123
  },
  'crónica15': {
    text: `EL PADRE OLEGARIO VILLALOBOS. “Una máquina puede hacer el trabajo de cincuenta hombres ordinarios, pero ninguna máquina puede hacer el trabajo de un hombre extraordinario. Del Señor decimos que pasó por la tierra haciendo el bien. Del padre Olegario Villalobos podemos decir que pasó por Maracaibo haciendo el bien”, así se refiere don Guillermo Bustamante, en su libro El Maracaibo de siempre, al muy querido y recordado presbítero padre Olegario Villalobos, quien nació en la calle Padre Añez, entre Ciencias y Providencia, el 26 de octubre de 1888. Este maracaibero vivió 89 años y 9 meses, de los cuales dedicó 58 años a trabajar con abnegación, entrega y amor por sus semejantes.`,
    words: [
        'EL', 'PADRE', 'OLEGARIO', 'VILLALOBOS', '“Una', 'máquina', 'puede', 'hacer', 'el', 'trabajo', 'de', 'cincuenta', 'hombres', 'ordinarios', 'pero', 'ninguna', 'máquina', 'puede', 'hacer', 'el', 'trabajo', 'de', 'un', 'hombre', 'extraordinario', 'Del', 'Señor', 'decimos', 'que', 'pasó', 'por', 'la', 'tierra', 'haciendo', 'el', 'bien', 'Del', 'padre', 'Olegario', 'Villalobos', 'podemos', 'decir', 'que', 'pasó', 'por', 'Maracaibo', 'haciendo', 'el', 'bien', 'así', 'se', 'refiere', 'don', 'Guillermo', 'Bustamante', 'en', 'su', 'libro', 'El', 'Maracaibo', 'de', 'siempre', 'al', 'muy', 'querido', 'y', 'recordado', 'presbítero', 'padre', 'Olegario', 'Villalobos', 'quien', 'nació', 'en', 'la', 'calle', 'Padre', 'Añez', 'entre', 'Ciencias', 'y', 'Providencia', 'el', '26', 'de', 'octubre', 'de', '1888', 'Este', 'maracaibero', 'vivió', '89', 'años', 'y', '9', 'meses', 'de', 'los', 'cuales', 'dedicó', '58', 'años', 'a', 'trabajar', 'con', 'abnegación', 'entrega', 'y', 'amor', 'por', 'sus', 'semejantes'
    ],
    wordCount: 132
  },
  'crónica17': {
    text: `MARACAIBO, PRIMERA CIUDAD DE VENEZUELA EN ERIGIR UNA ESTATUA AL LIBERTADOR. En 1867, Maracaibo tuvo el honor de ser la primera ciudad de Venezuela donde se erigió en una plaza pública, una estatua al Libertador Simón Bolívar.`,
    words: [
        'MARACAIBO', 'PRIMERA', 'CIUDAD', 'DE', 'VENEZUELA', 'EN', 'ERIGIR', 'UNA', 'ESTATUA', 'AL', 'LIBERTADOR', 'En', '1867', 'Maracaibo', 'tuvo', 'el', 'honor', 'de', 'ser', 'la', 'primera', 'ciudad', 'de', 'Venezuela', 'donde', 'se', 'erigió', 'en', 'una', 'plaza', 'pública', 'una', 'estatua', 'al', 'Libertador', 'Simón', 'Bolívar'
    ],
    wordCount: 37
  },
  'crónica18': {
    text: `MARACAIBO, PRIMERA CIUDAD EN CONTAR CON SERVICIO DE CORREO POSTAL. El primer correo postal que tuvo nuestra ciudad fue fundado el 7 de agosto de 1751, por decreto del marqués del Villar, virrey de Santa Fe de Bogotá. Maracaibo se convirtió entonces en la primera ciudad de Venezuela en contar con servicios de correos. Para esa fecha 1751, Maracaibo era una aldea de 4.800 habitantes, tenía 4 conventos, una iglesia y 1 hospital.`,
    words: [
        'MARACAIBO', 'PRIMERA', 'CIUDAD', 'EN', 'CONTAR', 'CON', 'SERVICIO', 'DE', 'CORREO', 'POSTAL', 'El', 'primer', 'correo', 'postal', 'que', 'tuvo', 'nuestra', 'ciudad', 'fue', 'fundado', 'el', '7', 'de', 'agosto', 'de', '1751', 'por', 'decreto', 'del', 'marqués', 'del', 'Villar', 'virrey', 'de', 'Santa', 'Fe', 'de', 'Bogotá', 'Maracaibo', 'se', 'convirtió', 'entonces', 'en', 'la', 'primera', 'ciudad', 'de', 'Venezuela', 'en', 'contar', 'con', 'servicios', 'de', 'correos', 'Para', 'esa', 'fecha', '1751', 'Maracaibo', 'era', 'una', 'aldea', 'de', '4', '800', 'habitantes', 'tenía', '4', 'conventos', 'una', 'iglesia', 'y', '1', 'hospital'
    ],
    wordCount: 77
  },
  'crónica19': {
    text: `HOSPITAL CENTRAL DR. URQUINAONA. Maracaibo es la ciudad que cuenta hoy con el hospital en funcionamiento más antiguo del país, el cual fue fundado en 1608 por los esposos don Francisco Hortiz y doña Inés de Bastos. Ha tenido varios nombres, el primero fue Hospital de Santa Ana, luego se llamó Hospital de Caridad, después casa de beneficencia y por último Hospital Central Dr. Urquinaona.`,
    words: [
        'HOSPITAL', 'CENTRAL', 'DR', 'URQUINAONA', 'Maracaibo', 'es', 'la', 'ciudad', 'que', 'cuenta', 'hoy', 'con', 'el', 'hospital', 'en', 'funcionamiento', 'más', 'antiguo', 'del', 'país', 'el', 'cual', 'fue', 'fundado', 'en', '1608', 'por', 'los', 'esposos', 'don', 'Francisco', 'Hortiz', 'y', 'doña', 'Inés', 'de', 'Bastos', 'Ha', 'tenido', 'varios', 'nombres', 'el', 'primero', 'fue', 'Hospital', 'de', 'Santa', 'Ana', 'luego', 'se', 'llamó', 'Hospital', 'de', 'Caridad', 'después', 'casa', 'de', 'beneficencia', 'y', 'por', 'último', 'Hospital', 'Central', 'Dr', 'Urquinaona'
    ],
    wordCount: 74
  },
  'crónica20': {
    text: `MARACAIBO, PRIMERA CIUDAD DE VENEZUELA EN PRACTICAR UNA OVARIOTOMÍA. La ovariotomía consiste en la extirpación de un ovario (unilateral), o ambos ovarios (bilateral). En 1874, el eminente médico, Dr. Francisco Eugenio Bustamante, tercer rector de la Universidad del Zulia, se constituye en el fundador de la cirugía abdominal, al practicar en esta ciudad de Maracaibo la primera ovariotomía.`,
    words: [
        'MARACAIBO', 'PRIMERA', 'CIUDAD', 'DE', 'VENEZUELA', 'EN', 'PRACTICAR', 'UNA', 'OVARIOTOMÍA', 'La', 'ovariotomía', 'consiste', 'en', 'la', 'extirpación', 'de', 'un', 'ovario', 'unilateral', 'o', 'ambos', 'ovarios', 'bilateral', 'En', '1874', 'el', 'eminente', 'médico', 'Dr', 'Francisco', 'Eugenio', 'Bustamante', 'tercer', 'rector', 'de', 'la', 'Universidad', 'del', 'Zulia', 'se', 'constituye', 'en', 'el', 'fundador', 'de', 'la', 'cirugía', 'abdominal', 'al', 'practicar', 'en', 'esta', 'ciudad', 'de', 'Maracaibo', 'la', 'primera', 'ovariotomía'
    ],
    wordCount: 71
  },
  'crónica21': {
    text: `FUNDACIÓN Y REFUNDACIONES DE MARACAIBO. Según las conclusiones a las cuales llegaron los historiadores en un simposio realizado especialmente para definir estos hechos, se estableció las siguientes son las fechas y fundadores de Maracaibo. Primera fundación: a cargo del conquistador alemán Ambrosio Alfinger, quien fundó Maracaibo el 08 de septiembre de 1529 con el nombre de Nueva Nuremberg de Nuestra Señora de la Laguna. Segunda fundación: a cargo del capitán Alonso Pacheco, quien refundó la ciudad en 1569, le dio el nombre de Ciudad Rodrigo. Tercera fundación: a cargo del capitán Pedro de Maldonado, quien refundó por última vez nuestra ciudad en 1574, dándole el nombre de Nueva Zamora de la Laguna de Maracaibo.`,
    words: [
        'FUNDACIÓN', 'Y', 'REFUNDACIONES', 'DE', 'MARACAIBO', 'Según', 'las', 'conclusiones', 'a', 'las', 'cuales', 'llegaron', 'los', 'historiadores', 'en', 'un', 'simposio', 'realizado', 'especialmente', 'para', 'definir', 'estos', 'hechos', 'se', 'estableció', 'las', 'siguientes', 'son', 'las', 'fechas', 'y', 'fundadores', 'de', 'Maracaibo', 'Primera', 'fundación', 'a', 'cargo', 'del', 'conquistador', 'alemán', 'Ambrosio', 'Alfinger', 'quien', 'fundó', 'Maracaibo', 'el', '08', 'de', 'septiembre', 'de', '1529', 'con', 'el', 'nombre', 'de', 'Nueva', 'Nuremberg', 'de', 'Nuestra', 'Señora', 'de', 'la', 'Laguna', 'Segunda', 'fundación', 'a', 'cargo', 'del', 'capitán', 'Alonso', 'Pacheco', 'quien', 'refundó', 'la', 'ciudad', 'en', '1569', 'le', 'dio', 'el', 'nombre', 'de', 'Ciudad', 'Rodrigo', 'Tercera', 'fundación', 'a', 'cargo', 'del', 'capitán', 'Pedro', 'de', 'Maldonado', 'quien', 'refundó', 'por', 'última', 'vez', 'nuestra', 'ciudad', 'en', '1574', 'dándole', 'el', 'nombre', 'de', 'Nueva', 'Zamora', 'de', 'la', 'Laguna', 'de', 'Maracaibo'
    ],
    wordCount: 138
  },
  'crónica22': {
    text: `MARACAIBO. Ciudad venezolana, capital del Estado Zulia, ubicada al noroeste de Venezuela, centro económico petrolero más importante del país y la segunda ciudad más poblada después de la capital de Venezuela, Caracas. Es el más importante municipio del Estado Zulia, posee 18 parroquias, con aproximadamente 1.653 millones (2015). Posee 393 kilómetros de extensión y está localizado al oeste del Lago de Maracaibo siendo el centro económico, financiero, político y militar del Estado Zulia de allí su gran importancia. Maracaibo nació a las orillas del Lago y se fue extendiendo desde allí a las partes más alejadas. Esta afirmación se comprueba en los hechos ocurridos durante las fundaciones y refundaciones de la ciudad que se dieron a las orillas del Lago. Los primeros mercados también fueron construidos a orillas del Lago, la primera colonia extranjera en establecerse fue la alemana y lo hicieron a las orillas del Lago en los sectores Haticos y El Milagro.`,
    words: [
        'MARACAIBO', 'Ciudad', 'venezolana', 'capital', 'del', 'Estado', 'Zulia', 'ubicada', 'al', 'noroeste', 'de', 'Venezuela', 'centro', 'económico', 'petrolero', 'más', 'importante', 'del', 'país', 'y', 'la', 'segunda', 'ciudad', 'más', 'poblada', 'después', 'de', 'la', 'capital', 'de', 'Venezuela', 'Caracas', 'Es', 'el', 'más', 'importante', 'municipio', 'del', 'Estado', 'Zulia', 'posee', '18', 'parroquias', 'con', 'aproximadamente', '1', '653', 'millones', '2015', 'Posee', '393', 'kilómetros', 'de', 'extensión', 'y', 'está', 'localizado', 'al', 'oeste', 'del', 'Lago', 'de', 'Maracaibo', 'siendo', 'el', 'centro', 'económico', 'financiero', 'político', 'y', 'militar', 'del', 'Estado', 'Zulia', 'de', 'allí', 'su', 'gran', 'importancia', 'Maracaibo', 'nació', 'a', 'las', 'orillas', 'del', 'Lago', 'y', 'se', 'fue', 'extendiendo', 'desde', 'allí', 'a', 'las', 'partes', 'más', 'alejadas', 'Esta', 'afirmación', 'se', 'comprueba', 'en', 'los', 'hechos', 'ocurridos', 'durante', 'las', 'fundaciones', 'y', 'refundaciones', 'de', 'la', 'ciudad', 'que', 'se', 'dieron', 'a', 'las', 'orillas', 'del', 'Lago', 'Los', 'primeros', 'mercados', 'también', 'fueron', 'construidos', 'a', 'orillas', 'del', 'Lago', 'la', 'primera', 'colonia', 'extranjera', 'en', 'establecerse', 'fue', 'la', 'alemana', 'y', 'lo', 'hicieron', 'a', 'las', 'orillas', 'del', 'Lago', 'en', 'los', 'sectores', 'Haticos', 'y', 'El', 'Milagro'
    ],
    wordCount: 171
  },
  'crónica23': {
    text: `EL TEMPLO DE CRISTO DE ARANZA. Fue declarado en 1960 Monumento Histórico Nacional. Como primera construcción eclesiástica es esencial para la iglesia católica venezolana. Su nombre se debe al Cristo de Aranza, cuya imagen tiene más de 450 años de haber llegado a la ciudad en un galeón que naufragó a orillas del Lago, justamente frente al lugar donde se alza la capilla sempiterna y como retando al tiempo, en cuanto a su estructura, es la iglesia más antigua de la ciudad. Se cree que fue construida en 1535 de palmeras y paja, en su interior se encontró la partitura de la gaita a “San Sebastián”, las más antigua conocida hasta los momentos. Según algunos el Templo fue el primero que se construyó en esta ciudad entre los años 1535 y 1555.`,
    words: [
        'EL', 'TEMPLO', 'DE', 'CRISTO', 'DE', 'ARANZA', 'Fue', 'declarado', 'en', '1960', 'Monumento', 'Histórico', 'Nacional', 'Como', 'primera', 'construcción', 'eclesiástica', 'es', 'esencial', 'para', 'la', 'iglesia', 'católica', 'venezolana', 'Su', 'nombre', 'se', 'debe', 'al', 'Cristo', 'de', 'Aranza', 'cuya', 'imagen', 'tiene', 'más', 'de', '450', 'años', 'de', 'haber', 'llegado', 'a', 'la', 'ciudad', 'en', 'un', 'galeón', 'que', 'naufragó', 'a', 'orillas', 'del', 'Lago', 'justamente', 'frente', 'al', 'lugar', 'donde', 'se', 'alza', 'la', 'capilla', 'sempiterna', 'y', 'como', 'retando', 'al', 'tiempo', 'en', 'cuanto', 'a', 'su', 'estructura', 'es', 'la', 'iglesia', 'más', 'antigua', 'de', 'la', 'ciudad', 'Se', 'cree', 'que', 'fue', 'construida', 'en', '1535', 'de', 'palmeras', 'y', 'paja', 'en', 'su', 'interior', 'se', 'encontró', 'la', 'partitura', 'de', 'la', 'gaita', 'a', 'San', 'Sebastián', 'las', 'más', 'antigua', 'conocida', 'hasta', 'los', 'momentos', 'Según', 'algunos', 'el', 'Templo', 'fue', 'el', 'primero', 'que', 'se', 'construyó', 'en', 'esta', 'ciudad', 'entre', 'los', 'años', '1535', 'y', '1555'
    ],
    wordCount: 179
},
  'crónica24': {
    text: `PANTEÓN DEL ESTADO ZULIA. Edificio considerado como el más elevado altar, donde se conservan los restos de personajes destacados en la historia de un pueblo. EL TEMPLO DE SAN FELIPE NERI se comenzó a construir en 1805 y fue inaugurado el 26 de mayo de 1835, en gran parte, la obra fue financiada por el señor José Simón Pena. En 1919, don Manuel Belloso Nava lo adquiere y lo dona a la Diócesis del Zulia. Desde principios de los años sesenta, el templo de San Felipe se encontraba cerrado y completamente abandonado, se convirtió en refugio de malvivientes, hasta 1988, cuando la Junta Presidencial para el Bicentenario del Gral. Rafael Urdaneta, propuso se convirtiera en Panteón Regional, donde descansaran los restos de las personalidades sobresalientes del Zulia, como homenaje póstumo. Para esa fecha, monseñor Gustavo Ocando Yamarte, presidente de la Corporación Niños Cantores del Zulia quien administraba el recinto, le dio el referido nombre por haber sido templo católico en dos ocasiones (Ermita de San Buenaventura y después Capilla de la Coromoto) y por haber trasladado allí el libro que contiene el Acta de Bautismo del General Rafael Urdaneta, prócer de la Independencia del Estado Zulia. Entonces se aprobó la Ley del Panteón del Estado Zulia, en la cual se ordenó que la sede del Panteón fuese el mal denominado Templo Bautismal.`,
    words: [
        'PANTEÓN', 'DEL', 'ESTADO', 'ZULIA', 'Edificio', 'considerado', 'como', 'el', 'más', 'elevado', 'altar', 'donde', 'se', 'conservan', 'los', 'restos', 'de', 'personajes', 'destacados', 'en', 'la', 'historia', 'de', 'un', 'pueblo', 'EL', 'TEMPLO', 'DE', 'SAN', 'FELIPE', 'NERI', 'se', 'comenzó', 'a', 'construir', 'en', '1805', 'y', 'fue', 'inaugurado', 'el', '26', 'de', 'mayo', 'de', '1835', 'en', 'gran', 'parte', 'la', 'obra', 'fue', 'financiada', 'por', 'el', 'señor', 'José', 'Simón', 'Pena', 'En', '1919', 'don', 'Manuel', 'Belloso', 'Nava', 'lo', 'adquiere', 'y', 'lo', 'dona', 'a', 'la', 'Diócesis', 'del', 'Zulia', 'Desde', 'principios', 'de', 'los', 'años', 'sesenta', 'el', 'templo', 'de', 'San', 'Felipe', 'se', 'encontraba', 'cerrado', 'y', 'completamente', 'abandonado', 'se', 'convirtió', 'en', 'refugio', 'de', 'malvivientes', 'hasta', '1988', 'cuando', 'la', 'Junta', 'Presidencial', 'para', 'el', 'Bicentenario', 'del', 'Gral', 'Rafael', 'Urdaneta', 'propuso', 'se', 'convirtiera', 'en', 'Panteón', 'Regional', 'donde', 'descansaran', 'los', 'restos', 'de', 'las', 'personalidades', 'sobresalientes', 'del', 'Zulia', 'como', 'homenaje', 'póstumo', 'Para', 'esa', 'fecha', 'monseñor', 'Gustavo', 'Ocando', 'Yamarte', 'presidente', 'de', 'la', 'Corporación', 'Niños', 'Cantores', 'del', 'Zulia', 'quien', 'administraba', 'el', 'recinto', 'le', 'dio', 'el', 'referido', 'nombre', 'por', 'haber', 'sido', 'templo', 'católico', 'en', 'dos', 'ocasiones', 'Ermita', 'de', 'San', 'Buenaventura', 'y', 'después', 'Capilla', 'de', 'la', 'Coromoto', 'y', 'por', 'haber', 'trasladado', 'allí', 'el', 'libro', 'que', 'contiene', 'el', 'Acta', 'de', 'Bautismo', 'del', 'General', 'Rafael', 'Urdaneta', 'prócer', 'de', 'la', 'Independencia', 'del', 'Estado', 'Zulia', 'Entonces', 'se', 'aprobó', 'la', 'Ley', 'del', 'Panteón', 'del', 'Estado', 'Zulia', 'en', 'la', 'cual', 'se', 'ordenó', 'que', 'la', 'sede', 'del', 'Panteón', 'fuese', 'el', 'mal', 'denominado', 'Templo', 'Bautismal'
    ],
    wordCount: 309
},
  'crónica25': {
    text: `PERSONALIDADES QUE REPOSAN EN EL PANTEÓN NACIONAL: Hasta ahora hay 12 personalidades inhumadas en el Panteón Regional del Zulia, el cual está conformado por 36 nichos cerrados y tres abiertos, todos de acero inoxidable y placas de bronce. Los cofres del General Rafael Urdaneta y Rafael María Baralt son simbólicos, pues sus restos se encuentran en el Panteón Nacional de Venezuela, Caracas. El General Venancio Pulgar fue el primer inhumado en 1955, después de 1997 llegaron los restos mortales de los próceres de la Independencia Anselmo Belloso Rodríguez, Juan Nepomuceno Santana y José de Jesús Infante. En el 2000 llegó Ricardo Aguirre, en el 2004 Udón Pérez y Francisco Ochoa, en 2009 José Antonio Chávez, en agosto de 2012 Julio Árraga, Manuel Puchi Fonseca y Adolfo de Pool; y en septiembre del mismo año ingresaron los restos de Felipe Pirela.`,
    words: [
        'PERSONALIDADES', 'QUE', 'REPOSAN', 'EN', 'EL', 'PANTEÓN', 'NACIONAL', 'Hasta', 'ahora', 'hay', '12', 'personalidades', 'inhumadas', 'en', 'el', 'Panteón', 'Regional', 'del', 'Zulia', 'el', 'cual', 'está', 'conformado', 'por', '36', 'nichos', 'cerrados', 'y', 'tres', 'abiertos', 'todos', 'de', 'acero', 'inoxidable', 'y', 'placas', 'de', 'bronce', 'Los', 'cofres', 'del', 'General', 'Rafael', 'Urdaneta', 'y', 'Rafael', 'María', 'Baralt', 'son', 'simbólicos', 'pues', 'sus', 'restos', 'se', 'encuentran', 'en', 'el', 'Panteón', 'Nacional', 'de', 'Venezuela', 'Caracas', 'El', 'General', 'Venancio', 'Pulgar', 'fue', 'el', 'primer', 'inhumado', 'en', '1955', 'después', 'de', '1997', 'llegaron', 'los', 'restos', 'mortales', 'de', 'los', 'próceres', 'de', 'la', 'Independencia', 'Anselmo', 'Belloso', 'Rodríguez', 'Juan', 'Nepomuceno', 'Santana', 'y', 'José', 'de', 'Jesús', 'Infante', 'En', 'el', '2000', 'llegó', 'Ricardo', 'Aguirre', 'en', 'el', '2004', 'Udón', 'Pérez', 'y', 'Francisco', 'Ochoa', 'en', '2009', 'José', 'Antonio', 'Chávez', 'en', 'agosto', 'de', '2012', 'Julio', 'Árraga', 'Manuel', 'Puchi', 'Fonseca', 'y', 'Adolfo', 'de', 'Pool', 'y', 'en', 'septiembre', 'del', 'mismo', 'año', 'ingresaron', 'los', 'restos', 'de', 'Felipe', 'Pirela'
    ],
    wordCount: 194
},
  'crónica26': {
    text: `GRACIELA RINCÓN CALCANO. 1904-1987 Brillante escritora, diplomática, poetisa, autora dramática y esforzada luchadora por los derechos de las mujeres, autora de la letra del Himno a la Virgen Chiquinquirá.`,
    words: [
        'GRACIELA', 'RINCÓN', 'CALCANO', '1904-1987', 'Brillante', 'escritora', 'diplomática', 'poetisa', 'autora', 'dramática', 'y', 'esforzada', 'luchadora', 'por', 'los', 'derechos', 'de', 'las', 'mujeres', 'autora', 'de', 'la', 'letra', 'del', 'Himno', 'a', 'la', 'Virgen', 'Chiquinquirá'
    ],
    wordCount: 29
},
  'crónica27': {
    text: `SAN SEBASTIÁN, PATRONO DE MARACAIBO. Santo, defensor y protector; considerado por el pueblo marabino creyente intercesor o abogado ante Dios. El patronazgo de San Sebastián fue impuesto a Maracaibo por la Corona Española como conmemoración del 20 de enero de 1569, fecha en la cual, según algunos historiadores el capitán Alonso Pacheco refundó la ciudad y la bautizó con el nombre de Ciudad Rodrigo. Antiguamente, ese día era celebrado muy solemnemente, pero al definirse en el simposio convocado para tales fines, se determinó que históricamente la verdadera fundación de la ciudad fue el 8 de septiembre de 1529 por el Alemán Ambrosio Alfinger, la celebración de la fundación se hace en esta fecha, sin embargo, hoy día se sigue conmemorando a cargo de la Alcaldía de Maracaibo, el día 20 de enero como “El Día del Patrono de la Ciudad"`,
    words: [
        'SAN', 'SEBASTIÁN', 'PATRONO', 'DE', 'MARACAIBO', 'Santo', 'defensor', 'y', 'protector', 'considerado', 'por', 'el', 'pueblo', 'marabino', 'creyente', 'intercesor', 'o', 'abogado', 'ante', 'Dios', 'El', 'patronazgo', 'de', 'San', 'Sebastián', 'fue', 'impuesto', 'a', 'Maracaibo', 'por', 'la', 'Corona', 'Española', 'como', 'conmemoración', 'del', '20', 'de', 'enero', 'de', '1569', 'fecha', 'en', 'la', 'cual', 'según', 'algunos', 'historiadores', 'el', 'capitán', 'Alonso', 'Pacheco', 'refundó', 'la', 'ciudad', 'y', 'la', 'bautizó', 'con', 'el', 'nombre', 'de', 'Ciudad', 'Rodrigo', 'Antiguamente', 'ese', 'día', 'era', 'celebrado', 'muy', 'solemnemente', 'pero', 'al', 'definirse', 'en', 'el', 'simposio', 'convocado', 'para', 'tales', 'fines', 'se', 'determinó', 'que', 'históricamente', 'la', 'verdadera', 'fundación', 'de', 'la', 'ciudad', 'fue', 'el', '8', 'de', 'septiembre', 'de', '1529', 'por', 'el', 'Alemán', 'Ambrosio', 'Alfinger', 'la', 'celebración', 'de', 'la', 'fundación', 'se', 'hace', 'en', 'esta', 'fecha', 'sin', 'embargo', 'hoy', 'día', 'se', 'sigue', 'conmemorando', 'a', 'cargo', 'de', 'la', 'Alcaldía', 'de', 'Maracaibo', 'el', 'día', '20', 'de', 'enero', 'como', 'El', 'Día', 'del', 'Patrono', 'de', 'la', 'Ciudad'
    ],
    wordCount: 153
},
  'crónica28': {
    text: `¿QUIÉN FUE SAN SEBASTIÁN? Fue un soldado romano (256-288) quien, debido a sus convicciones cristianas, fue condenado a la tortura y a ser flechado por sus compañeros de armas hasta morir. Maracaibo venera a su Patrono San Sebastián por sus milagros, en especial, por la curación de los enfermos y por la protección de la ciudad durante la peste negra de los años 1799-1844. Probablemente nuestra Santa Iglesia Catedral llevó su nombre por algún tiempo debido a que la imagen de San Sebastián presidia el altar mayor de la Catedral. Inclusive, la Plaza Bolívar se llamó en un tiempo Plaza de San Sebastián.`,
    words: [
        '¿QUIÉN', 'FUE', 'SAN', 'SEBASTIÁN', 'Fue', 'un', 'soldado', 'romano', '256-288', 'quien', 'debido', 'a', 'sus', 'convicciones', 'cristianas', 'fue', 'condenado', 'a', 'la', 'tortura', 'y', 'a', 'ser', 'flechado', 'por', 'sus', 'compañeros', 'de', 'armas', 'hasta', 'morir', 'Maracaibo', 'venera', 'a', 'su', 'Patrono', 'San', 'Sebastián', 'por', 'sus', 'milagros', 'en', 'especial', 'por', 'la', 'curación', 'de', 'los', 'enfermos', 'y', 'por', 'la', 'protección', 'de', 'la', 'ciudad', 'durante', 'la', 'peste', 'negra', 'de', 'los', 'años', '1799-1844', 'Probablemente', 'nuestra', 'Santa', 'Iglesia', 'Catedral', 'llevó', 'su', 'nombre', 'por', 'algún', 'tiempo', 'debido', 'a', 'que', 'la', 'imagen', 'de', 'San', 'Sebastián', 'presidia', 'el', 'altar', 'mayor', 'de', 'la', 'Catedral', 'Inclusive', 'la', 'Plaza', 'Bolívar', 'se', 'llamó', 'en', 'un', 'tiempo', 'Plaza', 'de', 'San', 'Sebastián'
    ],
    wordCount: 109
},
  'crónica29': {
    text: `LAS PIRAGUAS DEL LAGO DE MARACAIBO. En la Maracaibo de ayer, antes de la llegada de las primeras embarcaciones a vapor, las piraguas fueron airosas embarcaciones de blanco velamen, que cruzaban de norte a sur y de este a oeste nuestro bello y rico lago, el más grande de América del Sur con sus 12.870 kilómetros cuadrados de extensión. Además de ser elemento vital para la comunicación y el comercio, las piraguas fueron por muchos años emblema de Maracaibo, de la ciudad puerto, ya que las vistas que identificaban a nuestra ciudad siempre incluían los malecones con sus blancos y esbeltas piraguas.`,
    words: [
        'LAS', 'PIRAGUAS', 'DEL', 'LAGO', 'DE', 'MARACAIBO', 'En', 'la', 'Maracaibo', 'de', 'ayer', 'antes', 'de', 'la', 'llegada', 'de', 'las', 'primeras', 'embarcaciones', 'a', 'vapor', 'las', 'piraguas', 'fueron', 'airosas', 'embarcaciones', 'de', 'blanco', 'velamen', 'que', 'cruzaban', 'de', 'norte', 'a', 'sur', 'y', 'de', 'este', 'a', 'oeste', 'nuestro', 'bello', 'y', 'rico', 'lago', 'el', 'más', 'grande', 'de', 'América', 'del', 'Sur', 'con', 'sus', '12.870', 'kilómetros', 'cuadrados', 'de', 'extensión', 'Además', 'de', 'ser', 'elemento', 'vital', 'para', 'la', 'comunicación', 'y', 'el', 'comercio', 'las', 'piraguas', 'fueron', 'por', 'muchos', 'años', 'emblema', 'de', 'Maracaibo', 'de', 'la', 'ciudad', 'puerto', 'ya', 'que', 'las', 'vistas', 'que', 'identificaban', 'a', 'nuestra', 'ciudad', 'siempre', 'incluían', 'los', 'malecones', 'con', 'sus', 'blancos', 'y', 'esbeltas', 'piraguas'
    ],
    wordCount: 117
},
  'crónica30': {
    'text': 'MARACAIBO INAUGURA SU PRIMER SERVICIO DE TRANVÍA. El 5 de octubre de 1884, se inauguró en Maracaibo el primer Servicio de Tranvía de tracción animal, con 2 carros y 18 mulas. Posteriormente se inauguraron los tranvías eléctricos que recorrían las rutas de los Haticos, El Milagro, Bella Vista y Delicias.',
    'words': [
        'MARACAIBO', 'INAUGURA', 'SU', 'PRIMER', 'SERVICIO', 'DE', 'TRANVÍA', 'El', '5', 'de', 'octubre', 'de', '1884', 'se', 'inauguró', 'en', 'Maracaibo', 'el', 'primer', 'Servicio', 'de', 'Tranvía', 'de', 'tracción', 'animal', 'con', '2', 'carros', 'y', '18', 'mulas', 'Posteriormente', 'se', 'inauguraron', 'los', 'tranvías', 'eléctricos', 'que', 'recorrían', 'las', 'rutas', 'de', 'los', 'Haticos', 'El', 'Milagro', 'Bella', 'Vista', 'y', 'Delicias'
    ],
    'wordCount': 51
},
'crónica31': {
    'text': 'MARACAIBO INAUGURA SU PRIMER FERROCARRIL. El 19 de septiembre de 1891 se inauguró el primer ferrocarril a vapor de Maracaibo con una extensión de 5 kilómetros. Su recorrido era a lo largo de Bella Vista y tenía 4 locomotoras y 10 vagones para pasajeros y cargas.',
    'words': [
        'MARACAIBO', 'INAUGURA', 'SU', 'PRIMER', 'FERROCARRIL', 'El', '19', 'de', 'septiembre', 'de', '1891', 'se', 'inauguró', 'el', 'primer', 'ferrocarril', 'a', 'vapor', 'de', 'Maracaibo', 'con', 'una', 'extensión', 'de', '5', 'kilómetros', 'Su', 'recorrido', 'era', 'a', 'lo', 'largo', 'de', 'Bella', 'Vista', 'y', 'tenía', '4', 'locomotoras', 'y', '10', 'vagones', 'para', 'pasajeros', 'y', 'cargas'
    ],
    'wordCount': 48
},
  'crónica32': {
    'text': 'EL SERVICIO DE FERRYS ENTRE MARACAIBO Y LA COSTA ORIENTAL DEL LAGO. El servicio de ferry entre Maracaibo y la Costa Oriental del Lago fue promovida por la compañía anónima llamada Transporte La Translacustre que comenzó sus operaciones en 1937. No fue hasta principios de 1939 cuando llegó a Maracaibo el primer ferry. A un costo de Bs. 500.000,00 fue bautizado con el nombre de “Coquivacoa” y puesto en servicio de inmediato. Tenía capacidad para 24 vehículos y 200 pasajeros. Hasta un doble viaje diariamente en la ruta Maracaibo-Cabimas-Maracaibo, empleaba hora y media mientras que los vaporcitos demoraban más de 2 horas y estaban sujetos a mayores riesgos. Los ferrys prestaron su valioso servicio de transporte lacustre hasta el lunes 27 de agosto de 1962, día en que se efectuaron los últimos viajes de Maracaibo a Palmarejo.',
    'words': [
        'EL', 'SERVICIO', 'DE', 'FERRYS', 'ENTRE', 'MARACAIBO', 'Y', 'LA', 'COSTA', 'ORIENTAL', 'DEL', 'LAGO', 'El', 'servicio', 'de', 'ferry', 'entre', 'Maracaibo', 'y', 'la', 'Costa', 'Oriental', 'del', 'Lago', 'fue', 'promovida', 'por', 'la', 'compañía', 'anónima', 'llamada', 'Transporte', 'La', 'Translacustre', 'que', 'comenzó', 'sus', 'operaciones', 'en', '1937', 'No', 'fue', 'hasta', 'principios', 'de', '1939', 'cuando', 'llegó', 'a', 'Maracaibo', 'el', 'primer', 'ferry', 'A', 'un', 'costo', 'de', 'Bs', '500.000,00', 'fue', 'bautizado', 'con', 'el', 'nombre', 'de', 'Coquivacoa', 'y', 'puesto', 'en', 'servicio', 'de', 'inmediato', 'Tenía', 'capacidad', 'para', '24', 'vehículos', 'y', '200', 'pasajeros', 'Hasta', 'un', 'doble', 'viaje', 'diariamente', 'en', 'la', 'ruta', 'Maracaibo-Cabimas-Maracaibo', 'empleaba', 'hora', 'y', 'media', 'mientras', 'que', 'los', 'vaporcitos', 'demoraban', 'más', 'de', '2', 'horas', 'y', 'estaban', 'sujetos', 'a', 'mayores', 'riesgos', 'Los', 'ferrys', 'prestaron', 'su', 'valioso', 'servicio', 'de', 'transporte', 'lacustre', 'hasta', 'el', 'lunes', '27', 'de', 'agosto', 'de', '1962', 'día', 'en', 'que', 'se', 'efectuaron', 'los', 'últimos', 'viajes', 'de', 'Maracaibo', 'a', 'Palmarejo'
    ],
    'wordCount': 185
},
  
'crónica33': {
    'text': 'LA PRIMERA BOTICA DE MARACAIBO. Conocidas hoy por el nombre de farmacias, la primera botica de nuestra ciudad fue fundada por el señor José Peña y Parra en 1814. Después existió la Botica Alemana que más tarde dio paso a la empresa Van Dissel Rode & Cía. Igualmente la Botica Inglesa fundada por el norteamericano William Cook. Entre estos farmaceutas, uno de los más recordados es el doctor Adolfo Colina nacido en Maracaibo.',
    'words': [
        'LA', 'PRIMERA', 'BOTICA', 'DE', 'MARACAIBO', 'Conocidas', 'hoy', 'por', 'el', 'nombre', 'de', 'farmacias', 'la', 'primera', 'botica', 'de', 'nuestra', 'ciudad', 'fue', 'fundada', 'por', 'el', 'señor', 'José', 'Peña', 'y', 'Parra', 'en', '1814', 'Después', 'existió', 'la', 'Botica', 'Alemana', 'que', 'más', 'tarde', 'dio', 'paso', 'a', 'la', 'empresa', 'Van', 'Dissel', 'Rode', 'y', 'Cía', 'Igualmente', 'la', 'Botica', 'Inglesa', 'fundada', 'por', 'el', 'norteamericano', 'William', 'Cook', 'Entre', 'estos', 'farmaceutas', 'uno', 'de', 'los', 'más', 'recordados', 'es', 'el', 'doctor', 'Adolfo', 'Colina', 'nacido', 'en', 'Maracaibo'
    ],
    'wordCount': 73
},
'crónica34': {
    'text': 'EL PRIMER PERIODICO PUBLICADO EN MARACAIBO. Fue un seminario llamado “El Correo Nacional”, el cual sale a la luz pública el 09 de junio de 1821, tres años después de haber circulado el periódico de Venezuela “El Correo del Orinoco”. La primera edición contaba solo con 2 páginas de 35x25 centímetros. El correo Nacional solo fue editado por cinco meses por falta de recursos. Regresa el 20 de enero de 1821. Su redactor fue José Demetrio Lossada y Gutiérrez de Celis quien fue el primer venezolano – zuliano en sufrir prisión en aras de la libertad de prensa por haber expresado su opinión de ciertos asuntos públicos.',
    'words': [
        'EL', 'PRIMER', 'PERIODICO', 'PUBLICADO', 'EN', 'MARACAIBO', 'Fue', 'un', 'seminario', 'llamado', 'El', 'Correo', 'Nacional', 'el', 'cual', 'sale', 'a', 'la', 'luz', 'pública', 'el', '09', 'de', 'junio', 'de', '1821', 'tres', 'años', 'después', 'de', 'haber', 'circulado', 'el', 'periódico', 'de', 'Venezuela', 'El', 'Correo', 'del', 'Orinoco', 'La', 'primera', 'edición', 'contaba', 'solo', 'con', '2', 'páginas', 'de', '35x25', 'centímetros', 'El', 'correo', 'Nacional', 'solo', 'fue', 'editado', 'por', 'cinco', 'meses', 'por', 'falta', 'de', 'recursos', 'Regresa', 'el', '20', 'de', 'enero', 'de', '1821', 'Su', 'redactor', 'fue', 'José', 'Demetrio', 'Lossada', 'y', 'Gutiérrez', 'de', 'Celis', 'quien', 'fue', 'el', 'primer', 'venezolano', 'zuliano', 'en', 'sufrir', 'prisión', 'en', 'aras', 'de', 'la', 'libertad', 'de', 'prensa', 'por', 'haber', 'expresado', 'su', 'opinión', 'de', 'ciertos', 'asuntos', 'públicos'
    ],
    'wordCount': 107
},
'crónica35': {
    'text': 'LA IGLESIA DE SANTA ANA. Fue fundada por Doña Inés de Basto en el año 1607. Un año después, ella y su esposo, acaudalados inmigrantes agricultores españoles, fundan el actual Hospital Central Dr. Urquinaona. En esa época estas construcciones representaban un trinomio inseparable, ya que, por mandato real al construir una ciudad, era necesario destinar un sitio para la iglesia, otro para un cementerio y otro para un hospital todos anexos, es decir, los cementerios y hospitales los edificaban al lado de las iglesias.',
    'words': [
        'LA', 'IGLESIA', 'DE', 'SANTA', 'ANA', 'Fue', 'fundada', 'por', 'Doña', 'Inés', 'de', 'Basto', 'en', 'el', 'año', '1607', 'Un', 'año', 'después', 'ella', 'y', 'su', 'esposo', 'acaudalados', 'inmigrantes', 'agricultores', 'españoles', 'fundan', 'el', 'actual', 'Hospital', 'Central', 'Dr', 'Urquinaona', 'En', 'esa', 'época', 'estas', 'construcciones', 'representaban', 'un', 'trinomio', 'inseparable', 'ya', 'que', 'por', 'mandato', 'real', 'al', 'construir', 'una', 'ciudad', 'era', 'necesario', 'destinar', 'un', 'sitio', 'para', 'la', 'iglesia', 'otro', 'para', 'un', 'cementerio', 'y', 'otro', 'para', 'un', 'hospital', 'todos', 'anexos', 'es', 'decir', 'los', 'cementerios', 'y', 'hospitales', 'los', 'edificaban', 'al', 'lado', 'de', 'las', 'iglesias'
    ],
    'wordCount': 107
},
'crónica36': {
    'text': 'SOPAS CRIOLLAS. El mondongo es la sopa criolla preparada con la panza de la res, acompañada del típico “reca’o de olla”; es decir, con las verduras y legumbres que ya conocemos. Otras sopas criollas que nos representan en el arte culinario son: el hervido de res, hervido de gallina, sancocho de pescado, la chanfaina, que se prepara con un picadillo de todas las partes de la asadura de cochino que resulta en una sopa muy sabrosa, la sopa de caraotas de todos los colores, la sopa de granos de diferentes tipos: arvejas, lentejas, quinchonchos, habas y la criollísima sopa de frijolillos en coco. Otras sopas muy comunes en Maracaibo eran: la sopa de arroz con jugo de carne, sopa de fideos con huevo, sopa de plátano verde especialmente para detener la diarrea, sopa de papas y, para niños y enfermos, la sopa de pan con leche y la sopa de pichón.',
    'words': [
        'SOPAS', 'CRIOLLAS', 'El', 'mondongo', 'es', 'la', 'sopa', 'criolla', 'preparada', 'con', 'la', 'panza', 'de', 'la', 'res', 'acompañada', 'del', 'típico', 'reca’o', 'de', 'olla', 'es', 'decir', 'con', 'las', 'verduras', 'y', 'legumbres', 'que', 'ya', 'conocemos', 'Otras', 'sopas', 'criollas', 'que', 'nos', 'representan', 'en', 'el', 'arte', 'culinario', 'son', 'el', 'hervido', 'de', 'res', 'hervido', 'de', 'gallina', 'sancocho', 'de', 'pescado', 'la', 'chanfaina', 'que', 'se', 'prepara', 'con', 'un', 'picadillo', 'de', 'todas', 'las', 'partes', 'de', 'la', 'asadura', 'de', 'cochino', 'que', 'resulta', 'en', 'una', 'sopa', 'muy', 'sabrosa', 'la', 'sopa', 'de', 'caraotas', 'de', 'todos', 'los', 'colores', 'la', 'sopa', 'de', 'granos', 'de', 'diferentes', 'tipos', 'arvejas', 'lentejas', 'quinchonchos', 'habas', 'y', 'la', 'criollísima', 'sopa', 'de', 'frijolillos', 'en', 'coco', 'Otras', 'sopas', 'muy', 'comunes', 'en', 'Maracaibo', 'eran', 'la', 'sopa', 'de', 'arroz', 'con', 'jugo', 'de', 'carne', 'sopa', 'de', 'fideos', 'con', 'huevo', 'sopa', 'de', 'plátano', 'verde', 'especialmente', 'para', 'detener', 'la', 'diarrea', 'sopa', 'de', 'papas', 'y', 'para', 'niños', 'y', 'enfermos', 'la', 'sopa', 'de', 'pan', 'con', 'leche', 'y', 'la', 'sopa', 'de', 'pichón'
    ],
    'wordCount': 189
},
'crónica37': {
    'text': 'LA COCINA MARABINA. Nuestra cocina marabina es una maravilla en arte culinario, a continuación, algunos platos que se preparaban y aun se preparan en la ciudad: carne frita, pabellón acompañado de arroz, carne mechada, plátano frito amarillo en tajadas, caraotas negras guisadas, yuca y queso. Lomo con papas, bistec de lomo, el más consumido de la gente acomodada de la época por su alto precio, y la especialidad de la cocina maracaibera: animales de cacería preparados en coco como conejo, venado, lapa, yaguasas, báquiros, palomitas, perdices y las iguanas.',
    'words': [
        'LA', 'COCINA', 'MARABINA', 'Nuestra', 'cocina', 'marabina', 'es', 'una', 'maravilla', 'en', 'arte', 'culinario', 'a', 'continuación', 'algunos', 'platos', 'que', 'se', 'preparaban', 'y', 'aun', 'se', 'preparan', 'en', 'la', 'ciudad', 'carne', 'frita', 'pabellón', 'acompañado', 'de', 'arroz', 'carne', 'mechada', 'plátano', 'frito', 'amarillo', 'en', 'tajadas', 'caraotas', 'negras', 'guisadas', 'yuca', 'y', 'queso', 'Lomo', 'con', 'papas', 'bistec', 'de', 'lomo', 'el', 'más', 'consumido', 'de', 'la', 'gente', 'acomodada', 'de', 'la', 'época', 'por', 'su', 'alto', 'precio', 'y', 'la', 'especialidad', 'de', 'la', 'cocina', 'maracaibera', 'animales', 'de', 'cacería', 'preparados', 'en', 'coco', 'como', 'conejo', 'venado', 'lapa', 'yaguasas', 'báquiros', 'palomitas', 'perdices', 'y', 'las', 'iguanas'
    ],
    'wordCount': 99
},
  'crónica38': {
    'text': 'CEMENTERIOS DE MARACAIBO. Como en todas las ciudades, al principio los cementerios estaban siempre al lado de las iglesias. Posteriormente, en la medida en que los pueblos fueron creciendo, se construyeron extramuros, es decir, detrás de los muros que protegían la ciudad para evitar así las epidemias y malos olores. Entre los cementerios de la ciudad tenemos: el cementerio Viejo, situado en la avenida El Tránsito, construido antes de 1876 y demolido en 1945 para edificar la Plaza Centenario en conmemoración de los 100 años de la muerte del Gral. Rafael Urdaneta; el cementerio El Cuadrado, construido en 1876; el Cementerio de los Ingleses hoy demolido, construido por el Cónsul Inglés Southerland en los terrenos que ocupa el estacionamiento del edificio del Diario Panorama; el Cementerio Municipal San José o El Redondo construido en 1925; el Cementerio Corazón de Jesús construido 1940, el cementerio El Edén construido en 1955 y el Cementerio Jardines La Chinita construido en 1976.',
    'words': ['CEMENTERIOS', 'DE', 'MARACAIBO', 'Como', 'en', 'todas', 'las', 'ciudades', 'al', 'principio', 'los', 'cementerios', 'estaban', 'siempre', 'al', 'lado', 'de', 'las', 'iglesias', 'Posteriormente', 'en', 'la', 'medida', 'en', 'que', 'los', 'pueblos', 'fueron', 'creciendo', 'se', 'construyeron', 'extramuros', 'es', 'decir', 'detrás', 'de', 'los', 'muros', 'que', 'protegían', 'la', 'ciudad', 'para', 'evitar', 'así', 'las', 'epidemias', 'y', 'malos', 'olores', 'Entre', 'los', 'cementerios', 'de', 'la', 'ciudad', 'tenemos', 'el', 'cementerio', 'Viejo', 'situado', 'en', 'la', 'avenida', 'El', 'Tránsito', 'construido', 'antes', 'de', '1876', 'y', 'demolido', 'en', '1945', 'para', 'edificar', 'la', 'Plaza', 'Centenario', 'en', 'conmemoración', 'de', 'los', '100', 'años', 'de', 'la', 'muerte', 'del', 'Gral', 'Rafael', 'Urdaneta', 'el', 'cementerio', 'El', 'Cuadrado', 'construido', 'en', '1876', 'el', 'Cementerio', 'de', 'los', 'Ingleses', 'hoy', 'demolido', 'construido', 'por', 'el', 'Cónsul', 'Inglés', 'Southerland', 'en', 'los', 'terrenos', 'que', 'ocupa', 'el', 'estacionamiento', 'del', 'edificio', 'del', 'Diario', 'Panorama', 'el', 'Cementerio', 'Municipal', 'San', 'José', 'o', 'El', 'Redondo', 'construido', 'en', '1925', 'el', 'Cementerio', 'Corazón', 'de', 'Jesús', 'construido', '1940', 'el', 'cementerio', 'El', 'Edén', 'construido', 'en', '1955', 'y', 'el', 'Cementerio', 'Jardines', 'La', 'Chinita', 'construido', 'en', '1976'],
    'wordCount': 179
},
'crónica39': {
    'text': 'GAITA. Género musical original del estado Zulia en Venezuela, declarado bien patrimonial. Se relaciona con la navidad, aunque hoy en día su género se ejecuta todo el año en estados como Zulia, Falcón y Trujillo. Sus instrumentos básicos son: furro o furruco, maracas, cuatro, charrasca y tambora. Vibrante, contagiosa, irreverente; es el símbolo musical de Maracaibo, es la alegría navideña que enciende a Venezuela y se acuna en el pecho de un pueblo.',
    'words': ['GAITA', 'Género', 'musical', 'original', 'del', 'estado', 'Zulia', 'en', 'Venezuela', 'declarado', 'bien', 'patrimonial', 'Se', 'relaciona', 'con', 'la', 'navidad', 'aunque', 'hoy', 'en', 'día', 'su', 'género', 'se', 'ejecuta', 'todo', 'el', 'año', 'en', 'estados', 'como', 'Zulia', 'Falcón', 'y', 'Trujillo', 'Sus', 'instrumentos', 'básicos', 'son', 'furro', 'o', 'furruco', 'maracas', 'cuatro', 'charrasca', 'y', 'tambora', 'Vibrante', 'contagiosa', 'irreverente', 'es', 'el', 'símbolo', 'musical', 'de', 'Maracaibo', 'es', 'la', 'alegría', 'navideña', 'que', 'enciende', 'a', 'Venezuela', 'y', 'se', 'acuna', 'en', 'el', 'pecho', 'de', 'un', 'pueblo'],
    'wordCount': 77
},
'crónica40': {
    'text': 'ESTATUA. Escultura que representa a una figura humana. En 1867, Maracaibo tuvo el honor de ser la Primera Ciudad de Venezuela donde se erigió en una plaza pública una estatua al Libertador Simón Bolívar.',
    'words': ['ESTATUA', 'Escultura', 'que', 'representa', 'a', 'una', 'figura', 'humana', 'En', '1867', 'Maracaibo', 'tuvo', 'el', 'honor', 'de', 'ser', 'la', 'Primera', 'Ciudad', 'de', 'Venezuela', 'donde', 'se', 'erigió', 'en', 'una', 'plaza', 'pública', 'una', 'estatua', 'al', 'Libertador', 'Simón', 'Bolívar'],
    'wordCount': 34
},
'crónica41': {
    'text': 'FUNDABIBLIOTECA: El 30 de septiembre del 2007, se procede a establecer el acta constitutiva de la Red de Bibliotecas de Jesús Enrique Lossada, con todas las bases legales que requería para funcionar. Fundabiblioteca, adscrita a la Alcaldía de Maracaibo, creada según decreto No. 258, es una institución sin fines de lucro dedicada a la promoción de la lectoescritura a través de las fuentes documentales e interactivas en los individuos de todas las edades del municipio Maracaibo.',
    'words': ['FUNDABIBLIOTECA', 'El', '30', 'de', 'septiembre', 'del', '2007', 'se', 'procede', 'a', 'establecer', 'el', 'acta', 'constitutiva', 'de', 'la', 'Red', 'de', 'Bibliotecas', 'de', 'Jesús', 'Enrique', 'Lossada', 'con', 'todas', 'las', 'bases', 'legales', 'que', 'requería', 'para', 'funcionar', 'Fundabiblioteca', 'adscrita', 'a', 'la', 'Alcaldía', 'de', 'Maracaibo', 'creada', 'según', 'decreto', 'No', '258', 'es', 'una', 'institución', 'sin', 'fines', 'de', 'lucro', 'dedicada', 'a', 'la', 'promoción', 'de', 'la', 'lectoescritura', 'a', 'través', 'de', 'las', 'fuentes', 'documentales', 'e', 'interactivas', 'en', 'los', 'individuos', 'de', 'todas', 'las', 'edades', 'del', 'municipio', 'Maracaibo'],
    'wordCount': 79
},
'crónica42': {
    'text': 'EL LIBERTADOR VISITA LA CIUDAD DE MARACAIBO. Libertador fue el título que le dio el ayuntamiento de Caracas a Simón Bolívar, cuando éste entró triunfante después de haber completado su famosa Campaña Admirable iniciada en Cartagena y con la cual siempre se le ha distinguido. Nuestro libertador, Simón Bolívar visitó dos veces la ciudad de Maracaibo, la primera fue en el mes de agosto de 1821. Iba de paso hacia Cúcuta, donde prestaría juramento como presidente de la Gran Colombia ante el Congreso. Estuvo 20 días, desde el 29 de agosto hasta el 18 de septiembre de 1821. Su segunda visita fue mucho más breve, pues apenas duró tres días. En esa oportunidad el Libertador se hospedó en la Casa Fuerte, que posteriormente fue el Convento de las Clarisas y; luego de remodelada, fue construido en su lugar el actual edificio del Banco de Venezuela. Entre la Av. 5 Urdaneta y la calle 97 Bolívar, en el año 1911, con motivo de la celebración del Centenario de nuestra Independencia, la Asociación de Estudiantes del Zulia colocó en la fachada del Banco de Venezuela una lápida en conmemoración de esta visita, la cual dice textualmente “En esta casa residió el Libertador en diciembre de 1826. Memoria de los estudiantes en el Centenario de la Independencia”. En la parte superior de la placa, un pensamiento del Libertador que decía: “Solo el pueblo conoce su bien y es dueño de su suerte, Bolívar”.',
    'words': ['EL', 'LIBERTADOR', 'VISITA', 'LA', 'CIUDAD', 'DE', 'MARACAIBO', 'Libertador', 'fue', 'el', 'título', 'que', 'le', 'dio', 'el', 'ayuntamiento', 'de', 'Caracas', 'a', 'Simón', 'Bolívar', 'cuando', 'éste', 'entró', 'triunfante', 'después', 'de', 'haber', 'completado', 'su', 'famosa', 'Campaña', 'Admirable', 'iniciada', 'en', 'Cartagena', 'y', 'con', 'la', 'cual', 'siempre', 'se', 'le', 'ha', 'distinguido', 'Nuestro', 'libertador', 'Simón', 'Bolívar', 'visitó', 'dos', 'veces', 'la', 'ciudad', 'de', 'Maracaibo', 'la', 'primera', 'fue', 'en', 'el', 'mes', 'de', 'agosto', 'de', '1821', 'Iba', 'de', 'paso', 'hacia', 'Cúcuta', 'donde', 'prestaría', 'juramento', 'como', 'presidente', 'de', 'la', 'Gran', 'Colombia', 'ante', 'el', 'Congreso', 'Estuvo', '20', 'días', 'desde', 'el', '29', 'de', 'agosto', 'hasta', 'el', '18', 'de', 'septiembre', 'de', '1821', 'Su', 'segunda', 'visita', 'fue', 'mucho', 'más', 'breve', 'pues', 'apenas', 'duró', 'tres', 'días', 'En', 'esa', 'oportunidad', 'el', 'Libertador', 'se', 'hospedó', 'en', 'la', 'Casa', 'Fuerte', 'que', 'posteriormente', 'fue', 'el', 'Convento', 'de', 'las', 'Clarisas', 'y', 'luego', 'de', 'remodelada', 'fue', 'construido', 'en', 'su', 'lugar', 'el', 'actual', 'edificio', 'del', 'Banco', 'de', 'Venezuela', 'Entre', 'la', 'Av', '5', 'Urdaneta', 'y', 'la', 'calle', '97', 'Bolívar', 'en', 'el', 'año', '1911', 'con', 'motivo', 'de', 'la', 'celebración', 'del', 'Centenario', 'de', 'nuestra', 'Independencia', 'la', 'Asociación', 'de', 'Estudiantes', 'del', 'Zulia', 'colocó', 'en', 'la', 'fachada', 'del', 'Banco', 'de', 'Venezuela', 'una', 'lápida', 'en', 'conmemoración', 'de', 'esta', 'visita', 'la', 'cual', 'dice', 'textualmente', '“En', 'esta', 'casa', 'residió', 'el', 'Libertador', 'en', 'diciembre', 'de', '1826', 'Memoria', 'de', 'los', 'estudiantes', 'en', 'el', 'Centenario', 'de', 'la', 'Independencia”', 'En', 'la', 'parte', 'superior', 'de', 'la', 'placa', 'un', 'pensamiento', 'del', 'Libertador', 'que', 'decía', '“Solo', 'el', 'pueblo', 'conoce', 'su', 'bien', 'y', 'es', 'dueño', 'de', 'su', 'suerte', 'Bolívar”'],
    'wordCount': 301
},
'crónica43': {
    'text': 'LA CALLE ANCHA. Bautizada por el pueblo como “La Calle Ancha” es la calle que hoy conocemos con el nombre “Callejón de los Pobres”. Fue la más ancha que tuvo nuestra ciudad de Maracaibo, se le conoció también como “Calle del Márquez de Santa Cruz” y por muchos años fue una de las más importantes de la época. Con el transcurrir del tiempo, tuvo muchos nombres oficiales hasta ser nombrada formalmente por el Concejo Municipal de la época “Calle Comercio” como un homenaje al laborioso gremio de comerciantes de la ciudad.',
    'words': ['LA', 'CALLE', 'ANCHA', 'Bautizada', 'por', 'el', 'pueblo', 'como', '“La', 'Calle', 'Ancha”', 'es', 'la', 'calle', 'que', 'hoy', 'conocemos', 'con', 'el', 'nombre', '“Callejón', 'de', 'los', 'Pobres”', 'Fue', 'la', 'más', 'ancha', 'que', 'tuvo', 'nuestra', 'ciudad', 'de', 'Maracaibo', 'se', 'le', 'conoció', 'también', 'como', '“Calle', 'del', 'Márquez', 'de', 'Santa', 'Cruz”', 'y', 'por', 'muchos', 'años', 'fue', 'una', 'de', 'las', 'más', 'importantes', 'de', 'la', 'época', 'Con', 'el', 'transcurrir', 'del', 'tiempo', 'tuvo', 'muchos', 'nombres', 'oficiales', 'hasta', 'ser', 'nombrada', 'formalmente', 'por', 'el', 'Concejo', 'Municipal', 'de', 'la', 'época', '“Calle', 'Comercio”', 'como', 'un', 'homenaje', 'al', 'laborioso', 'gremio', 'de', 'comerciantes', 'de', 'la', 'ciudad'],
    'wordCount': 101
},
'crónica44': {
    'text': 'EL TEATRO BARALT. Monumento de importancia arquitectónica, fundado el 24 de julio de 1883 en conmemoración de los 100 años del nacimiento del Libertador, edificado en honor al escritor zuliano Rafael María Baralt. En este teatro se presentó por primera vez en América el vitoscopio cinematógrafo y actuó el cantor Carlos Gardel, quien deleitó con sus tantos a la muy culta sociedad de mediados del siglo XIX, así como muchísimos otros grandes artistas de fama mundial. Don Rafael María Baralt fue historiador, escritor, político, poeta, filósofo, periodista e ingeniero militar. Fue el primer americano en ocupar un sillón en la Real Academia Española de la Lengua. Nuestro primer teatro y la plaza de nuestra ciudad llevan hoy su nombre.',
    'words': ['EL', 'TEATRO', 'BARALT', 'Monumento', 'de', 'importancia', 'arquitectónica', 'fundado', 'el', '24', 'de', 'julio', 'de', '1883', 'en', 'conmemoración', 'de', 'los', '100', 'años', 'del', 'nacimiento', 'del', 'Libertador', 'edificado', 'en', 'honor', 'al', 'escritor', 'zuliano', 'Rafael', 'María', 'Baralt', 'En', 'este', 'teatro', 'se', 'presentó', 'por', 'primera', 'vez', 'en', 'América', 'el', 'vitoscopio', 'cinematógrafo', 'y', 'actuó', 'el', 'cantor', 'Carlos', 'Gardel', 'quien', 'deleitó', 'con', 'sus', 'tantos', 'a', 'la', 'muy', 'culta', 'sociedad', 'de', 'mediados', 'del', 'siglo', 'XIX', 'así', 'como', 'muchísimos', 'otros', 'grandes', 'artistas', 'de', 'fama', 'mundial', 'Don', 'Rafael', 'María', 'Baralt', 'fue', 'historiador', 'escritor', 'político', 'poeta', 'filósofo', 'periodista', 'e', 'ingeniero', 'militar', 'Fue', 'el', 'primer', 'americano', 'en', 'ocupar', 'un', 'sillón', 'en', 'la', 'Real', 'Academia', 'Española', 'de', 'la', 'Lengua', 'Nuestro', 'primer', 'teatro', 'y', 'la', 'plaza', 'de', 'nuestra', 'ciudad', 'llevan', 'hoy', 'su', 'nombre'],
    'wordCount': 135
},
'crónica45': {
    'text': 'BARRIO EL SALADILLO. Barrio emblemático de Maracaibo, desaparecido a mitad de 1900 para dar paso a la modernización de la ciudad, cuna de personajes icónicos, cuyas casas tenían altos techos con tejas rojas, enormes puertas y ventanas y fachadas de colores vivos para apaciguar el calor del mediodía. Su nombre se debió por su ubicación al lado de una salida cercana a la ciudad de Maracaibo. La primera mención histórica sobre el barrio data de 1774. Durante los siglos XIX y XX, se desarrolló un estilo local de viviendas popular, adaptado a las condiciones climáticas de la ciudad, lo cual le dio un carácter autóctono y una entidad propia muy arraigada. El verdadero barrio El Saladillo estaba situado detrás de la Iglesia de San Juan de Dios y en la parte frontal de la misma iglesia.',
    'words': ['BARRIO', 'EL', 'SALADILLO', 'Barrio', 'emblemático', 'de', 'Maracaibo', 'desaparecido', 'a', 'mitad', 'de', '1900', 'para', 'dar', 'paso', 'a', 'la', 'modernización', 'de', 'la', 'ciudad', 'cuna', 'de', 'personajes', 'icónicos', 'cuyas', 'casas', 'tenían', 'altos', 'techos', 'con', 'tejas', 'rojas', 'enormes', 'puertas', 'y', 'ventanas', 'y', 'fachadas', 'de', 'colores', 'vivos', 'para', 'apaciguar', 'el', 'calor', 'del', 'mediodía', 'Su', 'nombre', 'se', 'debió', 'por', 'su', 'ubicación', 'al', 'lado', 'de', 'una', 'salida', 'cercana', 'a', 'la', 'ciudad', 'de', 'Maracaibo', 'La', 'primera', 'mención', 'histórica', 'sobre', 'el', 'barrio', 'data', 'de', '1774', 'Durante', 'los', 'siglos', 'XIX', 'y', 'XX', 'se', 'desarrolló', 'un', 'estilo', 'local', 'de', 'viviendas', 'popular', 'adaptado', 'a', 'las', 'condiciones', 'climáticas', 'de', 'la', 'ciudad', 'lo', 'cual', 'le', 'dio', 'un', 'carácter', 'autóctono', 'y', 'una', 'entidad', 'propia', 'muy', 'arraigada', 'El', 'verdadero', 'barrio', 'El', 'Saladillo', 'estaba', 'situado', 'detrás', 'de', 'la', 'Iglesia', 'de', 'San', 'Juan', 'de', 'Dios', 'y', 'en', 'la', 'parte', 'frontal', 'de', 'la', 'misma', 'iglesia'],
    'wordCount': 151
},
  'crónica46': {
    'text': 'LOS HATICOS. Hacia mediados de 1800 se convirtió poco a poco en la zona residencial de la burguesía zuliana. Esta faja costera del sur, vinculada a la ciudad por el Camino Real de los españoles cuando se abrió el camino más cercano a las riberas del Lago, se convertiría en el paseo principal de la ciudad hasta la primera mitad del siglo XX. Estuvo ocupada por pequeños hatos y casas de campo con instalaciones para baños en el Lago, a través de las llamadas “Planchadas” donde la clase alta pasaba sus fines de semana y días festivos, quienes más tarde fijarían definitivamente sus residencias allí.',
    'words': ['LOS', 'HATICOS', 'Hacia', 'mediados', 'de', '1800', 'se', 'convirtió', 'poco', 'a', 'poco', 'en', 'la', 'zona', 'residencial', 'de', 'la', 'burguesía', 'zuliana', 'Esta', 'faja', 'costera', 'del', 'sur', 'vinculada', 'a', 'la', 'ciudad', 'por', 'el', 'Camino', 'Real', 'de', 'los', 'españoles', 'cuando', 'se', 'abrió', 'el', 'camino', 'más', 'cercano', 'a', 'las', 'riberas', 'del', 'Lago', 'se', 'convertiría', 'en', 'el', 'paseo', 'principal', 'de', 'la', 'ciudad', 'hasta', 'la', 'primera', 'mitad', 'del', 'siglo', 'XX', 'Estuvo', 'ocupada', 'por', 'pequeños', 'hatos', 'y', 'casas', 'de', 'campo', 'con', 'instalaciones', 'para', 'baños', 'en', 'el', 'Lago', 'a', 'través', 'de', 'las', 'llamadas', '“Planchadas”', 'donde', 'la', 'clase', 'alta', 'pasaba', 'sus', 'fines', 'de', 'semana', 'y', 'días', 'festivos', 'quienes', 'más', 'tarde', 'fijarían', 'definitivamente', 'sus', 'residencias', 'allí'],
    'wordCount': 138
},
'crónica47': {
    'text': 'IGLESIA SANTA LUCIA. Fue construida en el siglo XIX inicialmente con una sola torre de estilo neogótico, cuenta además con el privilegio de ser cuna de las devociones más importantes de Maracaibo, la de Santa Lucía, virgen y mártir, patrona de la vista y de la garganta, devoción únicamente comparable a la que se profesa en honor a Nuestra Señora de la Chiquinquirá, patrona del Estado. La devoción a la Santa Virgen llegó a Maracaibo como parte de la vida, costumbres y cultura de los inmigrantes italianos, quienes le dieron a conocer entre los habitantes de El Empedrao. La procesión con la imagen de la Santa Virgen constituye una fiesta tradicional cada 13 de diciembre.',
    'words': ['IGLESIA', 'SANTA', 'LUCIA', 'Fue', 'construida', 'en', 'el', 'siglo', 'XIX', 'inicialmente', 'con', 'una', 'sola', 'torre', 'de', 'estilo', 'neogótico', 'cuenta', 'además', 'con', 'el', 'privilegio', 'de', 'ser', 'cuna', 'de', 'las', 'devociones', 'más', 'importantes', 'de', 'Maracaibo', 'la', 'de', 'Santa', 'Lucía', 'virgen', 'y', 'mártir', 'patrona', 'de', 'la', 'vista', 'y', 'de', 'la', 'garganta', 'devoción', 'únicamente', 'comparable', 'a', 'la', 'que', 'se', 'profesa', 'en', 'honor', 'a', 'Nuestra', 'Señora', 'de', 'la', 'Chiquinquirá', 'patrona', 'del', 'Estado', 'La', 'devoción', 'a', 'la', 'Santa', 'Virgen', 'llegó', 'a', 'Maracaibo', 'como', 'parte', 'de', 'la', 'vida', 'costumbres', 'y', 'cultura', 'de', 'los', 'inmigrantes', 'italianos', 'quienes', 'le', 'dieron', 'a', 'conocer', 'entre', 'los', 'habitantes', 'de', 'El', 'Empedrao', 'La', 'procesión', 'con', 'la', 'imagen', 'de', 'la', 'Santa', 'Virgen', 'constituye', 'una', 'fiesta', 'tradicional', 'cada', '13', 'de', 'diciembre'],
    'wordCount': 126
},
'crónica48': {
    'text': 'BASÍLICA DE NUESTRA SEÑORA DEL ROSARIO DE CHIQUINQUIRÁ Y SAN JUAN DE DIOS. Nuestra Basílica es el templo católico más concurrido del estado Zulia en Venezuela. Ubicada en el centro de la ciudad de Maracaibo. Una construcción dedicada a la Virgen del Chiquinquirá patrona del estado Zulia. La Basílica cuenta con tres naves, dos torres, un altar mayor, un presbiterio y numerosos nichos dedicados a numerosos santos. Su primera edificación fue una pequeña ermita de barro y paja, construida en 1686 por el capitán Juan de las Nieves Andrade en honor a San Juan de Dios de quien era devoto. Hoy es hogar del relato en el cual hizo la milagrosa aparición la Virgen de Chiquinquirá patrona de la ciudad por devoción y decreto del pueblo.',
    'words': ['BASÍLICA', 'DE', 'NUESTRA', 'SEÑORA', 'DEL', 'ROSARIO', 'DE', 'CHIQUINQUIRÁ', 'Y', 'SAN', 'JUAN', 'DE', 'DIOS', 'Nuestra', 'Basílica', 'es', 'el', 'templo', 'católico', 'más', 'concurrido', 'del', 'estado', 'Zulia', 'en', 'Venezuela', 'Ubicada', 'en', 'el', 'centro', 'de', 'la', 'ciudad', 'de', 'Maracaibo', 'Una', 'construcción', 'dedicada', 'a', 'la', 'Virgen', 'del', 'Chiquinquirá', 'patrona', 'del', 'estado', 'Zulia', 'La', 'Basílica', 'cuenta', 'con', 'tres', 'naves', 'dos', 'torres', 'un', 'altar', 'mayor', 'un', 'presbiterio', 'y', 'numerosos', 'nichos', 'dedicados', 'a', 'numerosos', 'santos', 'Su', 'primera', 'edificación', 'fue', 'una', 'pequeña', 'ermita', 'de', 'barro', 'y', 'paja', 'construida', 'en', '1686', 'por', 'el', 'capitán', 'Juan', 'de', 'las', 'Nieves', 'Andrade', 'en', 'honor', 'a', 'San', 'Juan', 'de', 'Dios', 'de', 'quien', 'era', 'devoto', 'Hoy', 'es', 'hogar', 'del', 'relato', 'en', 'el', 'cual', 'hizo', 'la', 'milagrosa', 'aparición', 'la', 'Virgen', 'de', 'Chiquinquirá', 'patrona', 'de', 'la', 'ciudad', 'por', 'devoción', 'y', 'decreto', 'del', 'pueblo'],
    'wordCount': 151
},
'crónica49': {
    'text': 'RELÁMPAGO DEL CATATUMBO SALVA A MARACAIBO DE UN ATAQUE PIRATA. En 1595, un ataque a la ciudad de Maracaibo por el famoso pirata inglés Francis Drake fue frustrado gracias al Relámpago del Catatumbo. Su luminosidad permitió a un vigía alertar a la guarnición, que logró repeler el ataque nocturno. De hecho, el Relámpago del Catatumbo fue durante varios siglos un faro natural que sirvió para orientar a los navegantes que procedentes de las Antillas Holandesas, o llegados a sus aguas desde otros puertos, tenían como destino el Golfo de Venezuela. El Relámpago del Catatumbo es un fenómeno atmosférico singular que se localiza al oeste del Lago de Maracaibo desde tiempos inmemoriales, como lo corrobora su emisión en las tradiciones orales de los pueblos aborígenes de esta región. El Relámpago del Catatumbo le dio al Zulia el Guinness World Record por ser el lugar del mundo donde se generan la mayor cantidad de relámpagos por kilómetros cuadrados al año. El certificado oficial fue entregado el 28 de enero del 2014, aprovechando el Día de la Zulianidad.',
    'words': ['RELÁMPAGO', 'DEL', 'CATATUMBO', 'SALVA', 'A', 'MARACAIBO', 'DE', 'UN', 'ATAQUE', 'PIRATA', 'En', '1595', 'un', 'ataque', 'a', 'la', 'ciudad', 'de', 'Maracaibo', 'por', 'el', 'famoso', 'pirata', 'inglés', 'Francis', 'Drake', 'fue', 'frustrado', 'gracias', 'al', 'Relámpago', 'del', 'Catatumbo', 'Su', 'luminosidad', 'permitió', 'a', 'un', 'vigía', 'alertar', 'a', 'la', 'guarnición', 'que', 'logró', 'repeler', 'el', 'ataque', 'nocturno', 'De', 'hecho', 'el', 'Relámpago', 'del', 'Catatumbo', 'fue', 'durante', 'varios', 'siglos', 'un', 'faro', 'natural', 'que', 'sirvió', 'para', 'orientar', 'a', 'los', 'navegantes', 'que', 'procedentes', 'de', 'las', 'Antillas', 'Holandesas', 'o', 'llegados', 'a', 'sus', 'aguas', 'desde', 'otros', 'puertos', 'tenían', 'como', 'destino', 'el', 'Golfo', 'de', 'Venezuela', 'El', 'Relámpago', 'del', 'Catatumbo', 'es', 'un', 'fenómeno', 'atmosférico', 'singular', 'que', 'se', 'localiza', 'al', 'oeste', 'del', 'Lago', 'de', 'Maracaibo', 'desde', 'tiempos', 'inmemoriales', 'como', 'lo', 'corrobora', 'su', 'emisión', 'en', 'las', 'tradiciones', 'orales', 'de', 'los', 'pueblos', 'aborígenes', 'de', 'esta', 'región', 'El', 'Relámpago', 'del', 'Catatumbo', 'le', 'dio', 'al', 'Zulia', 'el', 'Guinness', 'World', 'Record', 'por', 'ser', 'el', 'lugar', 'del', 'mundo', 'donde', 'se', 'generan', 'la', 'mayor', 'cantidad', 'de', 'relámpagos', 'por', 'kilómetros', 'cuadrados', 'al', 'año', 'El', 'certificado', 'oficial', 'fue', 'entregado', 'el', '28', 'de', 'enero', 'del', '2014', 'aprovechando', 'el', 'Día', 'de', 'la', 'Zulianidad'],
    'wordCount': 217
},
'crónica50': {
    'text': 'MARACAIBO ILUMINADA POR FAROLES. Antes de la introducción del servicio eléctrico, el alumbrado público de los marabinos lo constituyeron los faroles de kerosene, protagonistas indiscutibles de la iluminación nocturna del Maracaibo de antaño. Ubicados en las esquinas, se exigía a los dueños de casa, iluminaría en las noches, que se colocaban en las puertas y ventanas. Por esa razón la oscuridad se prestaba para hacer travesuras, crímenes y también para los cuentos de aparecidos como el Anima Sola, La Llorona, Mandinga, entre otros; que debido a las supersticiones y prejuicios eran creídos por la mayoría de las personas de entonces. De ese sistema de faroles se originó el nombre de la Calle Los Biombos, situada detrás del templo San Juan de Dios, en el corazón de El Saladillo.',
    'words': ['MARACAIBO', 'ILUMINADA', 'POR', 'FAROLES', 'Antes', 'de', 'la', 'introducción', 'del', 'servicio', 'eléctrico', 'el', 'alumbrado', 'público', 'de', 'los', 'marabinos', 'lo', 'constituyeron', 'los', 'faroles', 'de', 'kerosene', 'protagonistas', 'indiscutibles', 'de', 'la', 'iluminación', 'nocturna', 'del', 'Maracaibo', 'de', 'antaño', 'Ubicados', 'en', 'las', 'esquinas', 'se', 'exigía', 'a', 'los', 'dueños', 'de', 'casa', 'iluminaría', 'en', 'las', 'noches', 'que', 'se', 'colocaban', 'en', 'las', 'puertas', 'y', 'ventanas', 'Por', 'esa', 'razón', 'la', 'oscuridad', 'se', 'prestaba', 'para', 'hacer', 'travesuras', 'crímenes', 'y', 'también', 'para', 'los', 'cuentos', 'de', 'aparecidos', 'como', 'el', 'Anima', 'Sola', 'La', 'Llorona', 'Mandinga', 'entre', 'otros', 'que', 'debido', 'a', 'las', 'supersticiones', 'y', 'prejuicios', 'eran', 'creídos', 'por', 'la', 'mayoría', 'de', 'las', 'personas', 'de', 'entonces', 'De', 'ese', 'sistema', 'de', 'faroles', 'se', 'originó', 'el', 'nombre', 'de', 'la', 'Calle', 'Los', 'Biombos', 'situada', 'detrás', 'del', 'templo', 'San', 'Juan', 'de', 'Dios', 'en', 'el', 'corazón', 'de', 'El', 'Saladillo'],
    'wordCount': 160
},

};

function populateChroniclesSelect() {
  const chronicleSelect = document.getElementById('chronicleSelect');
  
  for (let i = 1; i <= 50; i++) {
    const option = document.createElement('option');
    option.value = `crónica${i}`;
    option.textContent = `Crónica #${i}`;
    chronicleSelect.appendChild(option);
  }
}

// Función para actualizar la lista de palabras basada en la crónica seleccionada
function updateWordList() {
  const chronicleSelect = document.getElementById('chronicleSelect');
  const wordSelect = document.getElementById('wordSelect');
  const selectedChronicleKey = chronicleSelect.value;

  wordSelect.innerHTML = ''; // Limpiamos las opciones existentes

  if (chronicles[selectedChronicleKey]) {
    const words = chronicles[selectedChronicleKey].words;
    chronicles[selectedChronicleKey].wordCount = words.length; // Actualizamos el conteo de palabras

    words.forEach((word, index) => {
      const option = document.createElement('option');
      option.value = word;
      option.textContent = `${word} (Palabra #${index + 1})`;
      wordSelect.appendChild(option);
    });
  }
}

// Función para verificar la palabra seleccionada contra la entrada del usuario
function verifyWord() {
  const wordSelect = document.getElementById('wordSelect');
  const selectedWord = wordSelect.value;
  const userInput = document.getElementById('userInput').value;
  const resultContainer = document.getElementById('resultContainer');

  // Comprobación básica de coincidencia exacta
  if (userInput === selectedWord) {
    resultContainer.innerHTML = `<span class="correct">¡Correcto! La palabra "${selectedWord}" ha sido bien deletreada.</span>`;
    return;
  }

  // Comprobación de mayúsculas/minúsculas
  if (userInput.toLowerCase() === selectedWord.toLowerCase()) {
    resultContainer.innerHTML = `<span class="incorrect">Casi correcto, pero ha habido un error en el uso de mayúsculas y minúsculas.</span>`;
    return;
  }

  // Comprobación de tildes y caracteres especiales
  if (normalizeString(userInput) === normalizeString(selectedWord)) {
    resultContainer.innerHTML = `<span class="incorrect">Casi correcto, pero ha habido un error en la utilización de las tildes.</span>`;
    return;
  }

  // Comprobación de letras mal ubicadas o errores de escritura más generales
  resultContainer.innerHTML = `<span class="incorrect">Incorrecto. Ha habido un error en la ubicación de las letras, has indicado una letra que no corresponde a la secuencia.</span>`;
}

// Función auxiliar para normalizar strings (quitar tildes y caracteres especiales)
function normalizeString(str) {
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
}


// Inicialización de la página
window.onload = function() {
  populateChroniclesSelect();
  updateWordList();
};

